# 00B — PostgreSQL Performance Quickcheck
Health check rápido, read-only y reusable para `bd_replica_crm`.

In [1]:
from __future__ import annotations
import sys, time
from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np

cwd = Path.cwd().resolve()
PROJECT_ROOT = cwd if (cwd / "pyproject.toml").exists() else cwd.parent
if not (PROJECT_ROOT / "pyproject.toml").exists():
    raise RuntimeError("Ejecuta este notebook dentro de bd_replica_crm.")

SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from replica_cygnus.settings import load_settings
from replica_cygnus.connections import connect_postgres

settings = load_settings(PROJECT_ROOT)
conn = connect_postgres(settings)

pd.set_option("display.max_columns",150)
pd.set_option("display.max_rows",150)
pd.set_option("display.width",220)

def df(sql, params=None):
    return pd.read_sql_query(sql, conn, params=params)

print("DB:", settings.postgres.database)

DB: medallio_dw

## 1. Servidor y sesiones activas

In [2]:
display(df("""
SELECT current_database() database,current_user user_name,version(),
       now() now,pg_postmaster_start_time() postmaster_start
"""))
activity=df("""
SELECT pid,usename,application_name,state,wait_event_type,wait_event,
       now()-query_start AS running_for,LEFT(query,500) query
FROM pg_stat_activity
WHERE datname=current_database() AND pid<>pg_backend_pid()
ORDER BY query_start
""")
display(activity)

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

      database user_name                                            version                              now                 postmaster_start
0  medallio_dw  postgres  PostgreSQL 18.4 on x86_64-windows, compiled by... 2026-09-07 04:56:13.061932+00:00 2026-09-04 01:46:28.987845+00:00

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

     pid   usename                            application_name   state wait_event_type  wait_event            running_for                                              query
0  18876  postgres         DBeaver 26.1.1 - Main <medallio_dw>    idle          Client  ClientRead 0 days 04:24:07.829937                                   SHOW search_path
1  17788  postgres  DBeaver 26.1.1 - SQLEditor <Script-47.sql>    idle          Client  ClientRead 0 days 04:24:07.519017         SET search_path = analytics,"$user",public
2   8568  postgres  DBeaver 26.1.1 - SQLEditor <Script-61.sql>    idle          Client  ClientRead 0 days 04:24:07.311310         SET search_path = analytics,"$user",public
3  16500  postgres  DBeaver 26.1.1 - SQLEditor <Script-62.sql>    idle          Client  ClientRead 0 days 04:19:59.213367  SELECT c.oid, a.attnum, a.attname, c.relname, ...
4  10600  postgres     DBeaver 26.1.1 - Metadata <medallio_dw>    idle          Client  ClientRead 0 days 04:19:59.126563  SELECT i.*,c.relnamespace FROM pg_catalog.pg_i...
5  35548  postgres  DBeaver 26.1.1 - SQLEditor <Script-63.sql>    idle          Client  ClientRead 0 days 02:58:53.890580  SELECT c.oid, a.attnum, a.attname, c.relname, ...
6  34008  postgres                      replica_redshift_local  active            None        None 0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
7  16924  postgres                      replica_redshift_local  active            Lock    relation 0 days 00:12:22.917462  CREATE INDEX IF NOT EXISTS ix_lead_evidence_de...

## 2. Locks

In [3]:
locks=df("""
SELECT a.pid,a.usename,a.state,l.locktype,l.mode,l.granted,c.relname,
       now()-a.query_start AS running_for,LEFT(a.query,300) query
FROM pg_locks l
JOIN pg_stat_activity a ON a.pid=l.pid
LEFT JOIN pg_class c ON c.oid=l.relation
WHERE a.datname=current_database()
ORDER BY l.granted,a.query_start
""")
locks

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

      pid   usename   state       locktype              mode  granted                            relname              running_for                                              query
0   16924  postgres  active       relation         ShareLock    False                      lead_evidence   0 days 00:12:22.917462  CREATE INDEX IF NOT EXISTS ix_lead_evidence_de...
1   34008  postgres  active       relation  RowExclusiveLock     True      ix_lead_evidence_project_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
2   34008  postgres  active       relation   AccessShareLock     True      ix_lead_evidence_advisor_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
3   34008  postgres  active       relation  RowExclusiveLock     True      ix_lead_evidence_advisor_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
4   34008  postgres  active       relation   AccessShareLock     True                 lead_evidence_pkey   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
5   34008  postgres  active       relation  RowExclusiveLock     True                 lead_evidence_pkey   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
6   34008  postgres  active       relation   AccessShareLock     True     ix_lead_evidence_document_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
7   34008  postgres  active       relation  RowExclusiveLock     True     ix_lead_evidence_document_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
8   34008  postgres  active       relation   AccessShareLock     True       ix_lead_evidence_decision_at   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
9   34008  postgres  active       relation  RowExclusiveLock     True       ix_lead_evidence_decision_at   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
10  34008  postgres  active     virtualxid     ExclusiveLock     True                               None   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
11  34008  postgres  active       relation   AccessShareLock     True      ix_lead_evidence_project_time   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
12  34008  postgres  active  transactionid     ExclusiveLock     True                               None   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
13  34008  postgres  active       relation   AccessShareLock     True                      lead_evidence   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
14  34008  postgres  active       relation  RowExclusiveLock     True                      lead_evidence   0 days 00:32:43.407889  \n        UPDATE features.lead_evidence e SET\...
15  16924  postgres  active     virtualxid     ExclusiveLock     True                               None   0 days 00:12:22.917462  CREATE INDEX IF NOT EXISTS ix_lead_evidence_de...
16  16924  postgres  active         object   AccessShareLock     True                               None   0 days 00:12:22.917462  CREATE INDEX IF NOT EXISTS ix_lead_evidence_de...
17   7636  postgres  active       relation   AccessShareLock     True                           pg_class -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
18   7636  postgres  active     virtualxid     ExclusiveLock     True                               None -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
19   7636  postgres  active       relation   AccessShareLock     True                          pg_authid -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
20   7636  postgres  active       relation   AccessShareLock     True          pg_database_datname_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
21   7636  postgres  active       relation   AccessShareLock     True              pg_database_oid_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
22   7636  postgres  active       relation   AccessShareLock     True                pg_authid_oid_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
23   7636  postgres  active       relation   AccessShareLock     True            pg_authid_rolname_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
24   7636  postgres  active       relation   AccessShareLock     True                        pg_database -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
25   7636  postgres  active       relation   AccessShareLock     True                           pg_locks -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
26   7636  postgres  active       relation   AccessShareLock     True                 pg_class_oid_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
27   7636  postgres  active       relation   AccessShareLock     True  pg_class_tblspc_relfilenode_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
28   7636  postgres  active       relation   AccessShareLock     True                   pg_stat_activity -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...
29   7636  postgres  active       relation   AccessShareLock     True         pg_class_relname_nsp_index -1 days +23:59:59.923044  \nSELECT pid,usename,application_name,state,wa...

## 3. Tablas más grandes

In [4]:
table_sizes=df("""
SELECT n.nspname schema,c.relname table,c.reltuples::bigint approx_rows,
       pg_total_relation_size(c.oid) total_bytes,
       pg_indexes_size(c.oid) index_bytes,
       pg_size_pretty(pg_total_relation_size(c.oid)) total_size
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE c.relkind='r' AND n.nspname NOT IN ('pg_catalog','information_schema')
ORDER BY total_bytes DESC LIMIT 50
""")
table_sizes

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

                   schema                                   table  approx_rows  total_bytes  index_bytes total_size
0              raw_cygnus                           interacciones       798213    335077376     26066944     320 MB
1                features                           lead_evidence       205947    231628800     73195520     221 MB
2              raw_cygnus                      clientes_proyectos       204102     76783616      6569984      73 MB
3              raw_cygnus                                clientes       141512     73367552      4505600      70 MB
4              raw_cygnus                         proforma_unidad        44100     17940480      1048576      17 MB
5              raw_cygnus                               proformas        37891     11878400       892928      11 MB
6               analytics          fact_absorcion_proyecto_diario        22812      8314880      1343488    8120 kB
7              raw_cygnus                                procesos         5146      6094848       524288    5952 kB
8              raw_cygnus                            datos_extras        22429      4505600      1138688    4400 kB
9              raw_cygnus                                unidades         3237      4349952       245760    4248 kB
10              analytics              fact_stock_ofertado_diario        22812      4325376      1343488    4224 kB
11          observability                          quality_checks         8368      3342336      1548288    3264 kB
12             raw_cygnus  procesos_backup_keyfix_20260812_002329         4921      2834432            0    2768 kB
13              analytics                  fact_movimientos_stock         6530      2048000       548864    2000 kB
14                   core                              dim_unidad         3237      1335296       458752    1304 kB
15            etl_control                               sync_runs         2136       917504       393216     896 kB
16          observability                         asset_snapshots         2129       851968       368640     832 kB
17              analytics                     fact_ventas_detalle         1080       540672       212992     528 kB
18              analytics              int_ciclo_comercial_unidad         2007       540672        98304     528 kB
19            raw_mercado                      unidades_historial          696       507904       204800     496 kB
20              analytics                int_unidad_entrada_stock         2720       458752        90112     448 kB
21          observability              absorption_quality_results         2049       450560        65536     440 kB
22            raw_mercado                                unidades          696       393216        90112     384 kB
23              analytics                     int_proforma_minuta         1175       311296        65536     304 kB
24              analytics                               dim_fecha         2507       311296        73728     304 kB
25  decision_intelligence                          recommendation           69       196608        49152     192 kB
26              analytics                      agg_ventas_mensual          453       163840        81920     160 kB
27          observability                          asset_registry            9       131072        16384     128 kB
28       platform_control                      readiness_controls           23       114688        49152     112 kB
29                   core                            dim_proyecto           18        81920        65536      80 kB
30            etl_control                              sync_state            9        73728        16384      72 kB
31       platform_control                    application_registry           12        73728        16384      72 kB
32            raw_mercado                                  cargas           -1        65536        49152      64 kB
33            etl_control                     business_exclusions           -1        49152        32768      48 kB
34              analytics                      metric_definitions           -1        32768        16384      32 kB
35  decision_intelligence                         policy_registry           -1        32768        16384      32 kB
36              analytics          dim_periodo_comercial_proyecto           -1        32768        16384      32 kB
37       platform_control                              milestones           -1        32768        16384      32 kB
38  decision_intelligence                             lead_scores           -1        32768        24576      32 kB
39  decision_intelligence                         recommendations           -1        32768        24576      32 kB
40  decision_intelligence                      decision_contracts           -1        32768        16384      32 kB
41          model_control                              model_runs           -1        24576        16384      24 kB
42  decision_intelligence             candidate_universe_snapshot           -1        24576        16384      24 kB
43          model_control                         scoring_batches           -1        24576        16384      24 kB
44  decision_intelligence                            decision_run           -1        24576        16384      24 kB
45  decision_intelligence                                outcomes           -1        24576        16384      24 kB
46            experiments                             assignments           -1        16384         8192      16 kB
47             raw_cygnus                               proyectos           -1        16384            0      16 kB
48            experiments                             experiments           -1        16384         8192      16 kB
49  decision_intelligence                 recommendation_feedback           -1        16384         8192      16 kB

## 4. Sequential scans / index scans

In [5]:
scan_stats=df("""
SELECT schemaname schema,relname table,seq_scan,seq_tup_read,idx_scan,idx_tup_fetch,
       n_live_tup,n_dead_tup,
       CASE WHEN COALESCE(seq_scan,0)+COALESCE(idx_scan,0)=0 THEN NULL
            ELSE seq_scan::numeric/(seq_scan+idx_scan) END seq_scan_share
FROM pg_stat_user_tables
ORDER BY seq_tup_read DESC NULLS LAST
LIMIT 100
""")
scan_stats

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

                   schema                                   table  seq_scan  seq_tup_read   idx_scan  idx_tup_fetch  n_live_tup  n_dead_tup  seq_scan_share
0               analytics              int_ciclo_comercial_unidad   2884324    5785084390        8.0   0.000000e+00        2007           0        0.999997
1              raw_cygnus                                procesos     16169      82792656   112895.0   1.067344e+08        5148         478        0.125279
2              raw_cygnus                           interacciones       118      30535625    71952.0   7.909800e+04        2525       32005        0.001637
3              raw_cygnus                      clientes_proyectos       125       9653831    13641.0   1.292400e+04         717       10423        0.009080
4              raw_cygnus                                clientes        40       5372252    35834.0   3.529000e+04      141559       22589        0.001115
5                features                           lead_evidence        56       4698772  1162275.0   3.245070e+09      205947           0        0.000048
6              raw_cygnus                            datos_extras       215       4685015     4770.0   4.651000e+03       22429        2857        0.043129
7              raw_cygnus                         proforma_unidad       133       4474174     7835.0   7.415000e+03       44232        8390        0.016692
8              raw_cygnus                               proformas        40       1438286     6914.0   6.547000e+03       38008        6314        0.005752
9              raw_cygnus                                unidades       203        449070     3407.0   2.699600e+04        3237         249        0.056233
10              analytics                  fact_movimientos_stock        89        397784        0.0   0.000000e+00        6530           0        1.000000
11                   core                              dim_unidad       240        233064    13163.0   1.314700e+04        3237           0        0.017906
12              analytics                int_unidad_entrada_stock        57         78828    88949.0   9.437600e+04        2720           0        0.000640
13            raw_mercado                                unidades        57         20532      348.0   0.000000e+00         696           0        0.140741
14          observability                          quality_checks         1          8944        0.0   0.000000e+00        8980           0        1.000000
15              analytics                     int_proforma_minuta        35          8213        8.0   0.000000e+00        1175           0        0.813953
16            etl_control                              sync_state       640          5760      305.0   3.050000e+02           9          36        0.677249
17             raw_cygnus  procesos_backup_keyfix_20260812_002329         1          4921        NaN            NaN           0           0             NaN
18          observability                         asset_snapshots         2          4447     1332.0   1.332000e+03        2237           0        0.001499
19            etl_control                               sync_runs         2          4365      639.0   6.390000e+02        2196          21        0.003120
20              analytics                     fact_ventas_detalle         3          3240        0.0   0.000000e+00           0           0        1.000000
21                   core                            dim_proyecto       222          1548   106823.0   1.068230e+05          18           0        0.002074
22             raw_cygnus                               proyectos        71          1278        NaN            NaN          18           0             NaN
23              analytics                      agg_ventas_mensual         2           906        0.0   0.000000e+00           0           0        1.000000
24            raw_mercado                      unidades_historial         1           696        0.0   0.000000e+00         696           0        1.000000
25       platform_control                      readiness_controls        20           460       50.0   5.000000e+01          23          63        0.285714
26  decision_intelligence                          recommendation         2           138        0.0   0.000000e+00           0           0        1.000000
27       platform_control                    application_registry         3            36       28.0   2.800000e+01           0           0        0.096774
28              analytics          dim_periodo_comercial_proyecto         1            18        0.0   0.000000e+00           0           0        1.000000
29              analytics                      metric_definitions         3             9        0.0   0.000000e+00           0           0        1.000000
30          observability                          asset_registry         1             9     2331.0   2.331000e+03           9          32        0.000429
31       platform_control                              milestones         1             5       10.0   1.000000e+01           0           0        0.090909
32            raw_mercado                                  cargas         1             2      350.0   3.490000e+02           1           1        0.002849
33  decision_intelligence                      decision_contracts         1             1       16.0   1.500000e+01           1          13        0.058824
34  decision_intelligence                         policy_registry         1             1        0.0   0.000000e+00           0           0        1.000000
35            etl_control                     business_exclusions         1             1       84.0   8.400000e+01           0           0        0.011765
36  decision_intelligence                                 actions         5             0        0.0   0.000000e+00           0           0        1.000000
37  decision_intelligence                            decision_run         1             0        0.0   0.000000e+00           0           0        1.000000
38          model_control                         scoring_batches         2             0        0.0   0.000000e+00           0           0        1.000000
39          model_control                           model_aliases         1             0        0.0   0.000000e+00           0           0        1.000000
40  decision_intelligence                     production_incident         0             0        0.0   0.000000e+00           0           0             NaN
41              analytics          fact_absorcion_proyecto_diario         0             0        4.0   8.192000e+03           0           0        0.000000
42            experiments                             assignments         0             0        0.0   0.000000e+00           0           0             NaN
43  decision_intelligence                                outcomes         0             0        2.0   0.000000e+00           0           0        0.000000
44            experiments                             experiments         0             0        0.0   0.000000e+00           0           0             NaN
45              analytics                               dim_fecha         0             0        1.0   0.000000e+00           0           0        0.000000
46  decision_intelligence                  recommendation_outcome         0             0        0.0   0.000000e+00           0           0             NaN
47  decision_intelligence                   experiment_assignment         0             0        0.0   0.000000e+00           0           0             NaN
48  decision_intelligence                         recommendations         0             0       15.0   0.000000e+00           0           0        0.000000
49  decision_intelligence                     experiment_registry         1             0        0.0   0.000000e+00           0           0        1.000000
50          model_control                              model_runs         2             0        3.0   0.000000e+00           0           0        0.400000
51  decision_intelligence                             lead_scores         9             0        2.0   0.000000e+00           0           0        0.818182
52  decision_intelligence             candidate_universe_snapshot         0             0        0.0   0.000000e+00           0           0             NaN
53          model_control                        model_promotions         0             0        0.0   0.000000e+00           0           0             NaN
54  decision_intelligence                 recommendation_feedback         0             0        0.0   0.000000e+00           0           0             NaN
55  decision_intelligence                      quality_gate_event         0             0        0.0   0.000000e+00           0           0             NaN
56              analytics              fact_stock_ofertado_diario         0             0        4.0   8.192000e+03           0           0        0.000000
57          observability              absorption_quality_results         0             0        0.0   0.000000e+00        2049           0             NaN

## 5. Vacuum / Analyze

In [6]:
maintenance=df("""
SELECT schemaname schema,relname table,n_live_tup,n_dead_tup,
       CASE WHEN n_live_tup>0 THEN n_dead_tup::numeric/n_live_tup END dead_ratio,
       last_vacuum,last_autovacuum,last_analyze,last_autoanalyze
FROM pg_stat_user_tables
ORDER BY n_dead_tup DESC LIMIT 100
""")
maintenance

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

                   schema                                   table  n_live_tup  n_dead_tup  dead_ratio last_vacuum                  last_autovacuum last_analyze                 last_autoanalyze
0              raw_cygnus                           interacciones        2525       32005   12.675248        None                              NaT         None                              NaT
1              raw_cygnus                                clientes      141559       22589    0.159573        None                              NaT         None 2026-09-06 22:36:15.779475+00:00
2              raw_cygnus                      clientes_proyectos         717       10423   14.536960        None                              NaT         None                              NaT
3              raw_cygnus                         proforma_unidad       44232        8390    0.189682        None                              NaT         None 2026-09-06 19:59:25.260605+00:00
4              raw_cygnus                               proformas       38008        6314    0.166123        None                              NaT         None 2026-09-06 19:58:24.970108+00:00
5              raw_cygnus                            datos_extras       22429        2857    0.127380        None                              NaT         None 2026-09-07 04:36:50.354120+00:00
6              raw_cygnus                                procesos        5148         478    0.092852        None                              NaT         None 2026-09-06 22:35:13.603469+00:00
7              raw_cygnus                                unidades        3237         249    0.076923        None                              NaT         None 2026-09-07 02:35:23.834407+00:00
8        platform_control                      readiness_controls          23          63    2.739130        None 2026-09-07 04:55:50.032424+00:00         None 2026-09-07 04:32:49.519290+00:00
9             etl_control                              sync_state           9          36    4.000000        None                              NaT         None 2026-09-07 00:41:21.991485+00:00
10          observability                          asset_registry           9          32    3.555556        None                              NaT         None 2026-09-07 03:35:59.530129+00:00
11            etl_control                               sync_runs        2196          21    0.009563        None                              NaT         None 2026-09-06 22:35:13.240739+00:00
12  decision_intelligence                      decision_contracts           1          13   13.000000        None                              NaT         None                              NaT
13            raw_mercado                                  cargas           1           1    1.000000        None                              NaT         None                              NaT
14               features                           lead_evidence      205947           0    0.000000        None 2026-09-07 04:24:13.201467+00:00         None 2026-09-07 04:24:17.307911+00:00
15              analytics                  fact_movimientos_stock        6530           0    0.000000        None 2026-09-06 23:37:21.137465+00:00         None 2026-09-06 23:37:21.331487+00:00
16                   core                            dim_proyecto          18           0    0.000000        None                              NaT         None 2026-09-07 04:36:50.515514+00:00
17            experiments                             assignments           0           0         NaN        None                              NaT         None                              NaT
18       platform_control                    application_registry           0           0         NaN        None                              NaT         None                              NaT
19  decision_intelligence                                outcomes           0           0         NaN        None                              NaT         None                              NaT
20            experiments                             experiments           0           0         NaN        None                              NaT         None                              NaT
21              analytics                               dim_fecha           0           0         NaN        None                              NaT         None                              NaT
22  decision_intelligence                  recommendation_outcome           0           0         NaN        None                              NaT         None                              NaT
23              analytics          dim_periodo_comercial_proyecto           0           0         NaN        None                              NaT         None                              NaT
24  decision_intelligence                   experiment_assignment           0           0         NaN        None                              NaT         None                              NaT
25  decision_intelligence                         recommendations           0           0         NaN        None                              NaT         None                              NaT
26  decision_intelligence                     experiment_registry           0           0         NaN        None                              NaT         None                              NaT
27          model_control                              model_runs           0           0         NaN        None                              NaT         None                              NaT
28       platform_control                              milestones           0           0         NaN        None                              NaT         None                              NaT
29  decision_intelligence                             lead_scores           0           0         NaN        None                              NaT         None                              NaT
30  decision_intelligence             candidate_universe_snapshot           0           0         NaN        None                              NaT         None                              NaT
31          model_control                        model_promotions           0           0         NaN        None                              NaT         None                              NaT
32  decision_intelligence                 recommendation_feedback           0           0         NaN        None                              NaT         None                              NaT
33  decision_intelligence                      quality_gate_event           0           0         NaN        None                              NaT         None                              NaT
34  decision_intelligence                          recommendation           0           0         NaN        None                              NaT         None                              NaT
35              analytics                      agg_ventas_mensual           0           0         NaN        None                              NaT         None                              NaT
36              analytics              fact_stock_ofertado_diario           0           0         NaN        None                              NaT         None                              NaT
37              analytics                     int_proforma_minuta        1175           0    0.000000        None 2026-09-06 23:37:21.395321+00:00         None 2026-09-06 23:37:21.422886+00:00
38             raw_cygnus                               proyectos          18           0    0.000000        None                              NaT         None 2026-09-07 03:34:59.610070+00:00
39             raw_cygnus  procesos_backup_keyfix_20260812_002329           0           0         NaN        None                              NaT         None                              NaT
40          observability                         asset_snapshots        2237           0    0.000000        None                              NaT         None 2026-09-06 00:34:49.387041+00:00
41          observability              absorption_quality_results        2049           0    0.000000        None                              NaT         None 2026-09-06 23:37:21.114618+00:00
42            raw_mercado                      unidades_historial         696           0    0.000000        None                              NaT         None 2026-09-04 14:05:40.814905+00:00
43            raw_mercado                                unidades         696           0    0.000000        None                              NaT         None 2026-09-04 14:05:40.829759+00:00
44  decision_intelligence                                 actions           0           0         NaN        None                              NaT         None                              NaT
45          observability                          quality_checks        8980           0    0.000000        None                              NaT         None 2026-09-05 19:55:36.763050+00:00
46                   core                              dim_unidad        3237           0    0.000000        None 2026-09-07 04:36:50.366502+00:00         None 2026-09-07 04:36:50.503707+00:00
47              analytics              int_ciclo_comercial_unidad        2007           0    0.000000        None 2026-09-06 23:37:21.346895+00:00         None 2026-09-06 23:37:21.393059+00:00
48  decision_intelligence                            decision_run           0           0         NaN        None                              NaT         None                              NaT
49              analytics                     fact_ventas_detalle           0           0         NaN        None                              NaT         None                              NaT
50  decision_intelligence                         policy_registry           0           0         NaN        None                              NaT         None                              NaT
51          model_control                         scoring_batches           0           0         NaN        None                              NaT         None                              NaT
52              analytics                      metric_definitions           0           0         NaN        None                              NaT         None                              NaT
53              analytics                int_unidad_entrada_stock        2720           0    0.000000        None 2026-09-06 23:37:21.425933+00:00         None 2026-09-06 23:37:21.470622+00:00
54          model_control                           model_aliases           0           0         NaN        None                              NaT         None                              NaT
55  decision_intelligence                     production_incident           0           0         NaN        None                              NaT         None                              NaT
56            etl_control                     business_exclusions           0           0         NaN        None                              NaT         None                              NaT
57              analytics          fact_absorcion_proyecto_diario           0           0         NaN        None                              NaT         None                              NaT

## 6. Cache hit

In [7]:
cache=df("""
SELECT SUM(heap_blks_read) heap_read,SUM(heap_blks_hit) heap_hit,
       CASE WHEN SUM(heap_blks_hit)+SUM(heap_blks_read)=0 THEN NULL
            ELSE SUM(heap_blks_hit)::numeric/(SUM(heap_blks_hit)+SUM(heap_blks_read)) END cache_hit_ratio
FROM pg_statio_user_tables
""")
cache

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

   heap_read      heap_hit  cache_hit_ratio
0  2473868.0  1.664685e+09         0.998516

## 7. Índices usados / no usados

In [8]:
index_usage=df("""
SELECT s.schemaname schema,s.relname table,s.indexrelname index_name,s.idx_scan,
       pg_relation_size(i.indexrelid) index_bytes,
       pg_size_pretty(pg_relation_size(i.indexrelid)) index_size
FROM pg_stat_user_indexes s
JOIN pg_index i ON i.indexrelid=s.indexrelid
ORDER BY s.idx_scan ASC,index_bytes DESC
LIMIT 100
""")
index_usage

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

                   schema                           table                                         index_name  idx_scan  index_bytes  index_size
0                features                   lead_evidence                      ix_lead_evidence_advisor_time         0     12886016       12 MB
1           observability                  quality_checks                       ix_quality_checks_asset_time         0       811008      792 kB
2               analytics          fact_movimientos_stock                        fact_movimientos_stock_pkey         0       548864      536 kB
3           observability                  quality_checks                      ix_quality_checks_status_time         0       516096      504 kB
4           observability                  quality_checks                                quality_checks_pkey         0       221184      216 kB
5           observability                 asset_snapshots                      ix_asset_snapshots_asset_time         0       196608      192 kB
6             etl_control                       sync_runs                            ix_sync_runs_started_at         0       106496      104 kB
7           observability                 asset_snapshots                            ix_asset_snapshots_time         0       106496      104 kB
8                    core                      dim_unidad                                    dim_unidad_pkey         0       106496      104 kB
9               analytics             fact_ventas_detalle                           fact_ventas_detalle_pkey         0        90112       88 kB
10            raw_mercado              unidades_historial                 ix_unidades_historial_unidad_fecha         0        81920       80 kB
11              analytics             fact_ventas_detalle  fact_ventas_detalle_codigo_proforma_codigo_uni...         0        73728       72 kB
12            raw_mercado              unidades_historial   unidades_historial_snapshot_id_codigo_unidad_key         0        73728       72 kB
13          observability      absorption_quality_results                    absorption_quality_results_pkey         0        65536       64 kB
14                   core                      dim_unidad                  ix_dim_unidad_tipologia_ubicacion         0        57344       56 kB
15                   core                      dim_unidad                             ix_dim_unidad_proyecto         0        57344       56 kB
16                   core                      dim_unidad                                 ix_dim_unidad_tipo         0        57344       56 kB
17              analytics             fact_ventas_detalle                        ix_fact_ventas_project_date         0        49152       48 kB
18                   core                      dim_unidad                     ix_dim_unidad_estado_comercial         0        40960       40 kB
19              analytics              agg_ventas_mensual                            agg_ventas_mensual_pkey         0        40960       40 kB
20              analytics              agg_ventas_mensual                         ix_agg_sales_month_project         0        40960       40 kB
21            raw_mercado              unidades_historial                            unidades_historial_pkey         0        32768       32 kB
22                   core                    dim_proyecto                                  dim_proyecto_pkey         0        16384       16 kB
23              analytics              metric_definitions                            metric_definitions_pkey         0        16384       16 kB
24            etl_control             business_exclusions                           business_exclusions_pkey         0        16384       16 kB
25  decision_intelligence                  recommendation                           ix_recommendation_lookup         0        16384       16 kB
26                   core                    dim_proyecto                             ix_dim_proyecto_estado         0        16384       16 kB
27                   core                    dim_proyecto                           ix_dim_proyecto_distrito         0        16384       16 kB
28              analytics  dim_periodo_comercial_proyecto                dim_periodo_comercial_proyecto_pkey         0        16384       16 kB
29            raw_mercado                          cargas                             cargas_snapshot_id_key         0        16384       16 kB
30  decision_intelligence                 policy_registry                               policy_registry_pkey         0        16384       16 kB
31  decision_intelligence                  recommendation                       ux_recommendation_idempotent         0        16384       16 kB
32            raw_mercado              unidades_historial               ix_unidades_historial_proyecto_fecha         0        16384       16 kB
33            raw_mercado                        unidades                 ix_unidades_actual_proyecto_estado         0        16384       16 kB
34  decision_intelligence                  recommendation                                recommendation_pkey         0        16384       16 kB
35       platform_control              readiness_controls                       ix_readiness_controls_status         0        16384       16 kB
36          model_control                 scoring_batches                      ix_scoring_batches_model_time         0         8192  8192 bytes
37          model_control                      model_runs                                    model_runs_pkey         0         8192  8192 bytes
38  decision_intelligence                 recommendations                               recommendations_pkey         0         8192  8192 bytes
39  decision_intelligence                 recommendations                     ix_recommendations_system_time         0         8192  8192 bytes
40  decision_intelligence                         actions                                       actions_pkey         0         8192  8192 bytes
41  decision_intelligence                        outcomes                                      outcomes_pkey         0         8192  8192 bytes
42            experiments                     experiments                                   experiments_pkey         0         8192  8192 bytes
43            experiments                     assignments                                   assignments_pkey         0         8192  8192 bytes
44  decision_intelligence     candidate_universe_snapshot              ix_candidate_universe_snapshot_entity         0         8192  8192 bytes
45  decision_intelligence     candidate_universe_snapshot                   candidate_universe_snapshot_pkey         0         8192  8192 bytes
46  decision_intelligence             production_incident                           production_incident_pkey         0         8192  8192 bytes
47  decision_intelligence           experiment_assignment                         experiment_assignment_pkey         0         8192  8192 bytes
48  decision_intelligence             experiment_registry                           experiment_registry_pkey         0         8192  8192 bytes
49  decision_intelligence                    decision_run                             ix_decision_run_lookup         0         8192  8192 bytes
50  decision_intelligence                    decision_run                                  decision_run_pkey         0         8192  8192 bytes
51          model_control                 scoring_batches                               scoring_batches_pkey         0         8192  8192 bytes
52  decision_intelligence              quality_gate_event                            quality_gate_event_pkey         0         8192  8192 bytes
53  decision_intelligence          recommendation_outcome                        recommendation_outcome_pkey         0         8192  8192 bytes
54          model_control                   model_aliases                                 model_aliases_pkey         0         8192  8192 bytes
55  decision_intelligence         recommendation_feedback                       recommendation_feedback_pkey         0         8192  8192 bytes
56  decision_intelligence                     lead_scores          lead_scores_evidence_key_model_run_id_key         0         8192  8192 bytes
57  decision_intelligence                     lead_scores                                   lead_scores_pkey         0         8192  8192 bytes
58          model_control                model_promotions                              model_promotions_pkey         0         8192  8192 bytes
59              analytics  fact_absorcion_proyecto_diario                                ix_abs_project_date         1       598016      584 kB
60              analytics      fact_stock_ofertado_diario                         ix_fact_stock_project_date         1       598016      584 kB
61              analytics                       dim_fecha                                     dim_fecha_pkey         1        73728       72 kB
62            raw_mercado                          cargas                  cargas_source_id_hash_archivo_key         1        16384       16 kB
63  decision_intelligence                        outcomes                                 ix_outcomes_entity         2         8192  8192 bytes
64  decision_intelligence                     lead_scores                           ix_lead_scores_time_rank         2         8192  8192 bytes
65              analytics      fact_stock_ofertado_diario                    fact_stock_ofertado_diario_pkey         3       745472      728 kB
66              analytics  fact_absorcion_proyecto_diario                fact_absorcion_proyecto_diario_pkey         3       745472      728 kB
67          model_control                      model_runs                          ix_model_runs_system_time         3         8192  8192 bytes
68       platform_control              readiness_controls                          ix_readiness_controls_app         4        16384       16 kB
69              analytics      int_ciclo_comercial_unidad                    int_ciclo_comercial_unidad_pkey         8        98304       96 kB
70              analytics             int_proforma_minuta                           int_proforma_minuta_pkey         8        65536       64 kB
71       platform_control                      milestones                                    milestones_pkey        10        16384       16 kB
72  decision_intelligence                 recommendations                          ix_recommendations_entity        15         8192  8192 bytes
73  decision_intelligence              decision_contracts                            decision_contracts_pkey        16        16384       16 kB
74       platform_control            application_registry                          application_registry_pkey        28        16384       16 kB
75       platform_control              readiness_controls                            readiness_controls_pkey        46        16384       16 kB
76            etl_control             business_exclusions                      ux_business_exclusions_active        84        16384       16 kB
77            etl_control                      sync_state                                    sync_state_pkey       305        16384       16 kB
78            etl_control                       sync_runs                                     sync_runs_pkey       306        90112       88 kB
79            etl_control                       sync_runs                                 ix_sync_runs_table       333       196608      192 kB
80            raw_mercado                        unidades                                      unidades_pkey       348        73728       72 kB
81            raw_mercado                          cargas                                        cargas_pkey       349        16384       16 kB
82             raw_cygnus                        procesos                   ux_raw_cygnus_procesos_nombre_id       683       335872      328 kB
83          observability                 asset_snapshots                               asset_snapshots_pkey      1332        65536       64 kB
84          observability                  asset_registry                                asset_registry_pkey      2331        16384       16 kB
85             raw_cygnus                        unidades                              ux_replica_cd4ac4bac3      3407       245760      240 kB
86             raw_cygnus                    datos_extras                              ux_replica_1b1ff37f93      4770      1138688     1112 kB
87             raw_cygnus                       proformas                              ux_replica_5b59c2df49      6914       892928      872 kB
88             raw_cygnus                 proforma_unidad                              ux_replica_1a98092746      7835      1048576     1024 kB
89                   core                      dim_unidad                       dim_unidad_codigo_unidad_key     13163       139264      136 kB
90             raw_cygnus              clientes_proyectos                              ux_replica_2cbbec864c     13641      6569984     6416 kB
91             raw_cygnus                        clientes                              ux_replica_0d4fd6cf63     35834      4505600     4400 kB
92             raw_cygnus                   interacciones                              ux_replica_ec4b64dd30     71952     26066944       25 MB
93              analytics        int_unidad_entrada_stock                      int_unidad_entrada_stock_pkey     88949        90112       88 kB
94                   core                    dim_proyecto                   dim_proyecto_codigo_proyecto_key    106823        16384       16 kB
95             raw_cygnus                        procesos                              ux_replica_4d1ba85f02    112212       188416      184 kB
96               features                   lead_evidence                                 lead_evidence_pkey    222275     20602880       20 MB
97               features                   lead_evidence                       ix_lead_evidence_decision_at    268571     10027008     9792 kB
98               features                   lead_evidence                     ix_lead_evidence_document_time    268572     16973824       16 MB
99               features                   lead_evidence                      ix_lead_evidence_project_time    402857     12705792       12 MB

## 8. Foco lead scoring

In [9]:
lead_focus=df("""
SELECT n.nspname schema,c.relname table,c.reltuples::bigint approx_rows,
       pg_size_pretty(pg_total_relation_size(c.oid)) total_size
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE (n.nspname='features' AND c.relname='lead_evidence')
   OR (n.nspname='core' AND c.relname='fact_ciclo_comercial_unidad')
   OR (n.nspname='decision_intelligence' AND c.relname='lead_scores')
ORDER BY pg_total_relation_size(c.oid) DESC
""")
display(lead_focus)
lead_indexes=df("""
SELECT schemaname,tablename,indexname,indexdef
FROM pg_indexes
WHERE (schemaname='features' AND tablename='lead_evidence')
   OR (schemaname='core' AND tablename='fact_ciclo_comercial_unidad')
   OR (schemaname='decision_intelligence' AND tablename='lead_scores')
ORDER BY schemaname,tablename,indexname
""")
lead_indexes

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

                  schema                        table  approx_rows total_size
0               features                lead_evidence       205947     221 MB
1  decision_intelligence                  lead_scores           -1      32 kB
2                   core  fact_ciclo_comercial_unidad           -1    0 bytes

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\3726039764.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

              schemaname      tablename                                  indexname                                           indexdef
0  decision_intelligence    lead_scores                   ix_lead_scores_time_rank  CREATE INDEX ix_lead_scores_time_rank ON decis...
1  decision_intelligence    lead_scores  lead_scores_evidence_key_model_run_id_key  CREATE UNIQUE INDEX lead_scores_evidence_key_m...
2  decision_intelligence    lead_scores                           lead_scores_pkey  CREATE UNIQUE INDEX lead_scores_pkey ON decisi...
3               features  lead_evidence              ix_lead_evidence_advisor_time  CREATE INDEX ix_lead_evidence_advisor_time ON ...
4               features  lead_evidence               ix_lead_evidence_decision_at  CREATE INDEX ix_lead_evidence_decision_at ON f...
5               features  lead_evidence             ix_lead_evidence_document_time  CREATE INDEX ix_lead_evidence_document_time ON...
6               features  lead_evidence              ix_lead_evidence_project_time  CREATE INDEX ix_lead_evidence_project_time ON ...
7               features  lead_evidence                         lead_evidence_pkey  CREATE UNIQUE INDEX lead_evidence_pkey ON feat...

## 9. Diagnóstico automático

In [10]:
issues=[]
def add(sev,area,msg): issues.append({"severity":sev,"area":area,"message":msg})

longq=activity[pd.to_timedelta(activity["running_for"],errors="coerce")>pd.Timedelta(seconds=10)]
if len(longq): add("WARNING","queries",f"{len(longq)} query(s) >10s")
if len(locks[locks["granted"].eq(False)]): add("CRITICAL","locks","Hay locks no concedidos")
chr_=float(cache.iloc[0]["cache_hit_ratio"]) if pd.notna(cache.iloc[0]["cache_hit_ratio"]) else np.nan
if pd.notna(chr_) and chr_<0.95: add("WARNING","cache",f"Cache hit {chr_:.1%}")
high_seq=scan_stats[(scan_stats["seq_scan_share"].fillna(0)>.80)&(scan_stats["seq_tup_read"].fillna(0)>100000)]
if len(high_seq): add("WARNING","sequential_scans",f"{len(high_seq)} tabla(s) con alto sequential scan")
dead=maintenance[maintenance["dead_ratio"].fillna(0)>.20]
if len(dead): add("WARNING","vacuum",f"{len(dead)} tabla(s) con dead tuples >20%")
if not issues: add("OK","overall","Sin alertas fuertes")
diagnostic=pd.DataFrame(issues)
diagnostic

C:\Users\dinat\AppData\Local\Temp\ipykernel_27440\912920663.py:4: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
  longq=activity[pd.to_timedelta(activity["running_for"],errors="coerce")>pd.Timedelta(seconds=10)]

   severity              area                              message
0   WARNING           queries                      8 query(s) >10s
1  CRITICAL             locks              Hay locks no concedidos
2   WARNING  sequential_scans  2 tabla(s) con alto sequential scan
3   WARNING            vacuum      7 tabla(s) con dead tuples >20%

## 10. Top candidatos a optimización

In [11]:
candidates=scan_stats.merge(table_sizes[["schema","table","total_bytes","total_size"]],on=["schema","table"],how="left")
candidates["priority_score"]=candidates["seq_tup_read"].fillna(0)*candidates["seq_scan_share"].fillna(0)
candidates.sort_values("priority_score",ascending=False).head(30)

                   schema                           table  seq_scan  seq_tup_read   idx_scan  idx_tup_fetch  n_live_tup  n_dead_tup  seq_scan_share  total_bytes total_size  priority_score
0               analytics      int_ciclo_comercial_unidad   2884324    5785084390        8.0   0.000000e+00        2007           0        0.999997     540672.0     528 kB    5.785068e+09
1              raw_cygnus                        procesos     16169      82792656   112895.0   1.067344e+08        5148         478        0.125279    6094848.0    5952 kB    1.037218e+07
10              analytics          fact_movimientos_stock        89        397784        0.0   0.000000e+00        6530           0        1.000000    2048000.0    2000 kB    3.977840e+05
6              raw_cygnus                    datos_extras       215       4685015     4770.0   4.651000e+03       22429        2857        0.043129    4505600.0    4400 kB    2.020618e+05
3              raw_cygnus              clientes_proyectos       125       9653831    13641.0   1.292400e+04         717       10423        0.009080   76783616.0      73 MB    8.766010e+04
7              raw_cygnus                 proforma_unidad       133       4474174     7835.0   7.415000e+03       44232        8390        0.016692   17940480.0      17 MB    7.468187e+04
2              raw_cygnus                   interacciones       118      30535625    71952.0   7.909800e+04        2525       32005        0.001637  335077376.0     320 MB    4.999589e+04
9              raw_cygnus                        unidades       203        449070     3407.0   2.699600e+04        3237         249        0.056233    4349952.0    4248 kB    2.525241e+04
14          observability                  quality_checks         1          8944        0.0   0.000000e+00        8980           0        1.000000    3342336.0    3264 kB    8.944000e+03
8              raw_cygnus                       proformas        40       1438286     6914.0   6.547000e+03       38008        6314        0.005752   11878400.0      11 MB    8.273144e+03
15              analytics             int_proforma_minuta        35          8213        8.0   0.000000e+00        1175           0        0.813953     311296.0     304 kB    6.685000e+03
4              raw_cygnus                        clientes        40       5372252    35834.0   3.529000e+04      141559       22589        0.001115   73367552.0      70 MB    5.990134e+03
11                   core                      dim_unidad       240        233064    13163.0   1.314700e+04        3237           0        0.017906    1335296.0    1304 kB    4.173346e+03
16            etl_control                      sync_state       640          5760      305.0   3.050000e+02           9          36        0.677249      73728.0      72 kB    3.900952e+03
20              analytics             fact_ventas_detalle         3          3240        0.0   0.000000e+00           0           0        1.000000     540672.0     528 kB    3.240000e+03
13            raw_mercado                        unidades        57         20532      348.0   0.000000e+00         696           0        0.140741     393216.0     384 kB    2.889689e+03
23              analytics              agg_ventas_mensual         2           906        0.0   0.000000e+00           0           0        1.000000     163840.0     160 kB    9.060000e+02
24            raw_mercado              unidades_historial         1           696        0.0   0.000000e+00         696           0        1.000000     507904.0     496 kB    6.960000e+02
5                features                   lead_evidence        56       4698772  1162275.0   3.245070e+09      205947           0        0.000048  231628800.0     221 MB    2.263824e+02
26  decision_intelligence                  recommendation         2           138        0.0   0.000000e+00           0           0        1.000000     196608.0     192 kB    1.380000e+02
25       platform_control              readiness_controls        20           460       50.0   5.000000e+01          23          63        0.285714     114688.0     112 kB    1.314286e+02
12              analytics        int_unidad_entrada_stock        57         78828    88949.0   9.437600e+04        2720           0        0.000640     458752.0     448 kB    5.048195e+01
28              analytics  dim_periodo_comercial_proyecto         1            18        0.0   0.000000e+00           0           0        1.000000      32768.0      32 kB    1.800000e+01
19            etl_control                       sync_runs         2          4365      639.0   6.390000e+02        2196          21        0.003120     917504.0     896 kB    1.361934e+01
29              analytics              metric_definitions         3             9        0.0   0.000000e+00           0           0        1.000000      32768.0      32 kB    9.000000e+00
18          observability                 asset_snapshots         2          4447     1332.0   1.332000e+03        2237           0        0.001499     851968.0     832 kB    6.667166e+00
27       platform_control            application_registry         3            36       28.0   2.800000e+01           0           0        0.096774      73728.0      72 kB    3.483871e+00
21                   core                    dim_proyecto       222          1548   106823.0   1.068230e+05          18           0        0.002074      81920.0      80 kB    3.210388e+00
34  decision_intelligence                 policy_registry         1             1        0.0   0.000000e+00           0           0        1.000000      32768.0      32 kB    1.000000e+00
31       platform_control                      milestones         1             5       10.0   1.000000e+01           0           0        0.090909      32768.0      32 kB    4.545455e-01

In [12]:
conn.close(); print("Conexión cerrada.")

Conexión cerrada.