# BD Replica CRM — Command Center Notebook

Visión ejecutiva + técnica de `bd_replica_crm` desde VS Code.

**Objetivos**
- Ver si PostgreSQL local está vivo y qué tan fresco está.
- Inventariar esquemas, tablas, vistas y tamaños.
- Detectar tablas grandes, vacías o potencialmente obsoletas.
- Encontrar columnas temporales y estimar frescura.
- Revisar calidad básica: nulos, PKs y duplicados.
- Exponer objetos de observabilidad / Decision Intelligence si existen.
- Descubrir automáticamente objetos CRM/comerciales.
- Mantener todo en modo **solo lectura**.

## 0. Cómo ejecutarlo en VS Code

1. Coloca este archivo en `bd_replica_crm/notebooks/`.
2. Abre la raíz de `bd_replica_crm` en VS Code.
3. Selecciona el entorno Python del proyecto.
4. Si aún no instalaste el paquete local: `pip install -e .`
5. Asegúrate de tener `.env` configurado.
6. Ejecuta **Run All**.

> Usa `load_settings()` y `connect_postgres()` del propio repo. No guarda credenciales en el notebook.

In [1]:
from __future__ import annotations

import sys
import time
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd

cwd = Path.cwd().resolve()
PROJECT_ROOT = cwd if (cwd / "pyproject.toml").exists() else cwd.parent
if not (PROJECT_ROOT / "pyproject.toml").exists():
    raise RuntimeError(
        "No encuentro pyproject.toml. Abre este notebook dentro del repo bd_replica_crm."
    )

SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from replica_cygnus.settings import load_settings
from replica_cygnus.connections import connect_postgres

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 160)

settings = load_settings(PROJECT_ROOT)

print("Repo:", PROJECT_ROOT)
print(
    "PostgreSQL:",
    f"{settings.postgres.host}:{settings.postgres.port}/{settings.postgres.database}",
)
print("Notebook iniciado:", datetime.now().astimezone().isoformat(timespec="seconds"))

Repo: C:\AI\replica_redshift_local\replica_redshift_local
PostgreSQL: localhost:5432/medallio_dw
Notebook iniciado: 2026-09-06T22:04:02-05:00

In [2]:
conn = connect_postgres(settings)

def df(sql: str, params=None) -> pd.DataFrame:
    t0 = time.perf_counter()
    out = pd.read_sql_query(sql, conn, params=params)
    out.attrs["elapsed_s"] = time.perf_counter() - t0
    return out

server = df("""
SELECT
    current_database() AS database,
    current_user AS usuario,
    version() AS version,
    now() AS server_now,
    pg_postmaster_start_time() AS postgres_started_at
""")

server

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

      database   usuario                                            version                       server_now              postgres_started_at
0  medallio_dw  postgres  PostgreSQL 18.4 on x86_64-windows, compiled by... 2026-09-07 03:04:02.716835+00:00 2026-09-04 01:46:28.987845+00:00

## 1. KPI técnico inmediato

In [3]:
kpi = df("""
WITH rel AS (
    SELECT
        n.nspname AS schema_name,
        c.relname AS object_name,
        c.relkind,
        pg_total_relation_size(c.oid) AS bytes
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
      AND n.nspname NOT LIKE 'pg_toast%'
      AND c.relkind IN ('r','p','v','m')
)
SELECT
    COUNT(DISTINCT schema_name) AS schemas,
    COUNT(*) FILTER (WHERE relkind IN ('r','p')) AS tables,
    COUNT(*) FILTER (WHERE relkind = 'v') AS views,
    COUNT(*) FILTER (WHERE relkind = 'm') AS materialized_views,
    pg_size_pretty(SUM(bytes)) AS total_size
FROM rel
""")

kpi

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

   schemas  tables  views  materialized_views total_size
0       11      58     50                   0     753 MB

## 2. Mapa completo del Data Warehouse local

In [4]:
inventory = df("""
SELECT
    n.nspname AS schema_name,
    c.relname AS object_name,
    CASE c.relkind
        WHEN 'r' THEN 'table'
        WHEN 'p' THEN 'partitioned_table'
        WHEN 'v' THEN 'view'
        WHEN 'm' THEN 'materialized_view'
        ELSE c.relkind::text
    END AS object_type,
    COALESCE(s.n_live_tup, c.reltuples)::bigint AS approx_rows,
    pg_total_relation_size(c.oid) AS bytes,
    pg_size_pretty(pg_total_relation_size(c.oid)) AS total_size,
    s.last_analyze,
    s.last_autoanalyze,
    s.last_vacuum,
    s.last_autovacuum
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_stat_user_tables s ON s.relid = c.oid
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND c.relkind IN ('r','p','v','m')
ORDER BY pg_total_relation_size(c.oid) DESC, n.nspname, c.relname
""")

inventory.head(30)

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

,schema_name,object_name,object_type,approx_rows,bytes,total_size,last_analyze,last_autoanalyze,last_vacuum,last_autovacuum
0,raw_cygnus,interacciones,table,2525,335077376,320 MB,None,NaT,None,NaT
1,features,lead_evidence,table,205947,231104512,220 MB,None,2026-09-07 02:40:10.734095+00:00,None,2026-09-07 02:40:06.485480+00:00
2,raw_cygnus,clientes_proyectos,table,717,76587008,73 MB,None,NaT,None,NaT
3,raw_cygnus,clientes,table,141559,73367552,70 MB,None,2026-09-06 22:36:15.779475+00:00,None,NaT
4,raw_cygnus,proforma_unidad,table,44232,17940480,17 MB,None,2026-09-06 19:59:25.260605+00:00,None,NaT
5,raw_cygnus,proformas,table,38008,11878400,11 MB,None,2026-09-06 19:58:24.970108+00:00,None,NaT
6,analytics,fact_absorcion_proyecto_diario,table,0,8314880,8120 kB,None,NaT,None,NaT
7,raw_cygnus,procesos,table,5148,6094848,5952 kB,None,2026-09-06 22:35:13.603469+00:00,None,NaT
8,raw_cygnus,datos_extras,table,22429,4505600,4400 kB,None,2026-09-05 10:47:32.547843+00:00,None,NaT
9,raw_cygnus,unidades,table,3237,4349952,4248 kB,None,2026-09-07 02:35:23.834407+00:00,None,NaT
10,analytics,fact_stock_ofertado_diario,table,0,4325376,4224 kB,None,NaT,None,NaT
11,observability,quality_checks,table,8908,3334144,3256 kB,None,2026-09-05 19:55:36.763050+00:00,None,NaT
12,raw_cygnus,procesos_backup_keyfix_20260812_002329,table,0,2834432,2768 kB,None,NaT,None,NaT
13,analytics,fact_movimientos_stock,table,6530,2048000,2000 kB,None,2026-09-06 23:37:21.331487+00:00,None,2026-09-06 23:37:21.137465+00:00
14,core,dim_unidad,table,3237,1335296,1304 kB,None,2026-09-07 02:40:10.938783+00:00,None,2026-09-07 02:40:10.747520+00:00
15,etl_control,sync_runs,table,2178,917504,896 kB,None,2026-09-06 22:35:13.240739+00:00,None,NaT
16,observability,asset_snapshots,table,2219,851968,832 kB,None,2026-09-06 00:34:49.387041+00:00,None,NaT
17,analytics,fact_ventas_detalle,table,0,540672,528 kB,None,NaT,None,NaT
18,analytics,int_ciclo_comercial_unidad,table,2007,540672,528 kB,None,2026-09-06 23:37:21.393059+00:00,None,2026-09-06 23:37:21.346895+00:00
19,raw_mercado,unidades_historial,table,696,507904,496 kB,None,2026-09-04 14:05:40.814905+00:00,None,NaT
20,analytics,int_unidad_entrada_stock,table,2720,458752,448 kB,None,2026-09-06 23:37:21.470622+00:00,None,2026-09-06 23:37:21.425933+00:00
21,observability,absorption_quality_results,table,2049,450560,440 kB,None,2026-09-06 23:37:21.114618+00:00,None,NaT
22,raw_mercado,unidades,table,696,393216,384 kB,None,2026-09-04 14:05:40.829759+00:00,None,NaT
23,analytics,dim_fecha,table,0,311296,304 kB,None,NaT,None,NaT
24,analytics,int_proforma_minuta,table,1175,311296,304 kB,None,2026-09-06 23:37:21.422886+00:00,None,2026-09-06 23:37:21.395321+00:00
25,decision_intelligence,recommendation,table,0,196608,192 kB,None,NaT,None,NaT
26,analytics,agg_ventas_mensual,table,0,163840,160 kB,None,NaT,None,NaT
27,observability,asset_registry,table,9,131072,128 kB,None,2026-09-06 23:37:21.077267+00:00,None,NaT
28,platform_control,readiness_controls,table,0,114688,112 kB,None,NaT,None,NaT
29,core,dim_proyecto,table,18,81920,80 kB,None,2026-09-07 01:35:22.825985+00:00,None,NaT

In [5]:
schema_summary = (
    inventory.groupby("schema_name", as_index=False)
    .agg(
        objects=("object_name", "count"),
        approx_rows=("approx_rows", "sum"),
        bytes=("bytes", "sum"),
    )
    .sort_values("bytes", ascending=False)
)

schema_summary["size_mb"] = schema_summary["bytes"] / 1024**2
schema_summary

              schema_name  objects  approx_rows      bytes     size_mb
9              raw_cygnus       10       257873  532652032  507.976562
5                features       14       205934  231104512  220.398438
0               analytics       15        12428   17080320   16.289062
7           observability       11        13178    4767744    4.546875
1                    core        4         3253    1417216    1.351562
3             etl_control        3         2187    1040384    0.992188
10            raw_mercado        4         1392     966656    0.921875
2   decision_intelligence       35          -19     516096    0.492188
8        platform_control        5           -2     221184    0.210938
6           model_control        5           -1      81920    0.078125
4             experiments        2            0      32768    0.031250

### Tablas más pesadas

Útil para responder rápido: **¿dónde está el volumen real y qué podría estar haciendo lento un pipeline?**

In [6]:
largest = inventory.query("object_type in ['table','partitioned_table']").copy()
largest["size_mb"] = largest["bytes"] / 1024**2

largest[
    ["schema_name","object_name","approx_rows","size_mb","last_autoanalyze"]
].head(25)

      schema_name                             object_name  approx_rows     size_mb                 last_autoanalyze
0      raw_cygnus                           interacciones         2525  319.554688                              NaT
1        features                           lead_evidence       205947  220.398438 2026-09-07 02:40:10.734095+00:00
2      raw_cygnus                      clientes_proyectos          717   73.039062                              NaT
3      raw_cygnus                                clientes       141559   69.968750 2026-09-06 22:36:15.779475+00:00
4      raw_cygnus                         proforma_unidad        44232   17.109375 2026-09-06 19:59:25.260605+00:00
5      raw_cygnus                               proformas        38008   11.328125 2026-09-06 19:58:24.970108+00:00
6       analytics          fact_absorcion_proyecto_diario            0    7.929688                              NaT
7      raw_cygnus                                procesos         5148    5.812500 2026-09-06 22:35:13.603469+00:00
8      raw_cygnus                            datos_extras        22429    4.296875 2026-09-05 10:47:32.547843+00:00
9      raw_cygnus                                unidades         3237    4.148438 2026-09-07 02:35:23.834407+00:00
10      analytics              fact_stock_ofertado_diario            0    4.125000                              NaT
11  observability                          quality_checks         8908    3.179688 2026-09-05 19:55:36.763050+00:00
12     raw_cygnus  procesos_backup_keyfix_20260812_002329            0    2.703125                              NaT
13      analytics                  fact_movimientos_stock         6530    1.953125 2026-09-06 23:37:21.331487+00:00
14           core                              dim_unidad         3237    1.273438 2026-09-07 02:40:10.938783+00:00
15    etl_control                               sync_runs         2178    0.875000 2026-09-06 22:35:13.240739+00:00
16  observability                         asset_snapshots         2219    0.812500 2026-09-06 00:34:49.387041+00:00
17      analytics                     fact_ventas_detalle            0    0.515625                              NaT
18      analytics              int_ciclo_comercial_unidad         2007    0.515625 2026-09-06 23:37:21.393059+00:00
19    raw_mercado                      unidades_historial          696    0.484375 2026-09-04 14:05:40.814905+00:00
20      analytics                int_unidad_entrada_stock         2720    0.437500 2026-09-06 23:37:21.470622+00:00
21  observability              absorption_quality_results         2049    0.429688 2026-09-06 23:37:21.114618+00:00
22    raw_mercado                                unidades          696    0.375000 2026-09-04 14:05:40.829759+00:00
23      analytics                               dim_fecha            0    0.296875                              NaT
24      analytics                     int_proforma_minuta         1175    0.296875 2026-09-06 23:37:21.422886+00:00

## 3. Columnas, PKs e índices

In [7]:
columns = df("""
SELECT
    table_schema AS schema_name,
    table_name,
    ordinal_position,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema NOT IN ('pg_catalog','information_schema')
ORDER BY table_schema, table_name, ordinal_position
""")

columns.groupby("schema_name").agg(
    tables=("table_name","nunique"),
    columns=("column_name","count")
).sort_values("tables", ascending=False)

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

                       tables  columns
schema_name
decision_intelligence      35      526
analytics                  15      294
features                   14      314
observability              11      192
raw_cygnus                 10      429
platform_control            5       57
model_control               5       51
core                        4      138
raw_mercado                 4      115
etl_control                 3       38
experiments                 2       15

In [8]:
pk = df("""
SELECT
    ns.nspname AS schema_name,
    tbl.relname AS table_name,
    con.conname AS constraint_name,
    string_agg(att.attname, ', ' ORDER BY u.ord) AS pk_columns
FROM pg_constraint con
JOIN pg_class tbl ON tbl.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS u(attnum, ord)
JOIN pg_attribute att
  ON att.attrelid = tbl.oid
 AND att.attnum = u.attnum
WHERE con.contype = 'p'
  AND ns.nspname NOT IN ('pg_catalog','information_schema')
GROUP BY ns.nspname, tbl.relname, con.conname
ORDER BY ns.nspname, tbl.relname
""")

pk

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

              schema_name                      table_name                      constraint_name                                         pk_columns
0               analytics              agg_ventas_mensual              agg_ventas_mensual_pkey                       periodo_mes, codigo_proyecto
1               analytics                       dim_fecha                       dim_fecha_pkey                                              fecha
2               analytics  dim_periodo_comercial_proyecto  dim_periodo_comercial_proyecto_pkey                                    codigo_proyecto
3               analytics  fact_absorcion_proyecto_diario  fact_absorcion_proyecto_diario_pkey                             fecha, codigo_proyecto
4               analytics          fact_movimientos_stock          fact_movimientos_stock_pkey                                        movement_id
5               analytics      fact_stock_ofertado_diario      fact_stock_ofertado_diario_pkey                             fecha, codigo_proyecto
6               analytics             fact_ventas_detalle             fact_ventas_detalle_pkey                                           sale_key
7               analytics      int_ciclo_comercial_unidad      int_ciclo_comercial_unidad_pkey                     codigo_proforma, codigo_unidad
8               analytics             int_proforma_minuta             int_proforma_minuta_pkey                     codigo_proforma, codigo_unidad
9               analytics        int_unidad_entrada_stock        int_unidad_entrada_stock_pkey                                      codigo_unidad
10              analytics              metric_definitions              metric_definitions_pkey                                        metric_name
11                   core                    dim_proyecto                    dim_proyecto_pkey                                        proyecto_id
12                   core                      dim_unidad                      dim_unidad_pkey                                          unidad_id
13  decision_intelligence                         actions                         actions_pkey                                          action_id
14  decision_intelligence     candidate_universe_snapshot     candidate_universe_snapshot_pkey  decision_key, snapshot_at, entity_type, entity_id
15  decision_intelligence              decision_contracts              decision_contracts_pkey                                    decision_system
16  decision_intelligence                    decision_run                    decision_run_pkey                                             run_id
17  decision_intelligence           experiment_assignment           experiment_assignment_pkey             experiment_key, entity_type, entity_id
18  decision_intelligence             experiment_registry             experiment_registry_pkey                                     experiment_key
19  decision_intelligence                     lead_scores                     lead_scores_pkey                                           score_id
20  decision_intelligence                        outcomes                        outcomes_pkey                                         outcome_id
21  decision_intelligence                 policy_registry                 policy_registry_pkey                       decision_key, policy_version
22  decision_intelligence             production_incident             production_incident_pkey                                        incident_id
23  decision_intelligence              quality_gate_event              quality_gate_event_pkey                                      gate_event_id
24  decision_intelligence                  recommendation                  recommendation_pkey                                  recommendation_id
25  decision_intelligence         recommendation_feedback         recommendation_feedback_pkey                                        feedback_id
26  decision_intelligence          recommendation_outcome          recommendation_outcome_pkey                                  recommendation_id
27  decision_intelligence                 recommendations                 recommendations_pkey                                  recommendation_id
28            etl_control             business_exclusions             business_exclusions_pkey                                       exclusion_id
29            etl_control                       sync_runs                       sync_runs_pkey                                             run_id
30            etl_control                      sync_state                      sync_state_pkey  source_schema, source_table, target_schema, ta...
31            experiments                     assignments                     assignments_pkey                           experiment_id, entity_id
32            experiments                     experiments                     experiments_pkey                                      experiment_id
33               features                   lead_evidence                   lead_evidence_pkey                                       evidence_key
34          model_control                   model_aliases                   model_aliases_pkey            decision_system, model_name, alias_name
35          model_control                model_promotions                model_promotions_pkey                                       promotion_id
36          model_control                      model_runs                      model_runs_pkey                                       model_run_id
37          model_control                 scoring_batches                 scoring_batches_pkey                                   scoring_batch_id
38          observability      absorption_quality_results      absorption_quality_results_pkey                                  quality_result_id
39          observability                  asset_registry                  asset_registry_pkey                                          asset_key
40          observability                 asset_snapshots                 asset_snapshots_pkey                                        snapshot_id
41          observability                  quality_checks                  quality_checks_pkey                                   quality_check_id
42       platform_control            application_registry            application_registry_pkey                                            app_key
43       platform_control                      milestones                      milestones_pkey                                      milestone_key
44       platform_control              readiness_controls              readiness_controls_pkey                                        control_key
45            raw_mercado                          cargas                          cargas_pkey                                           carga_id
46            raw_mercado                        unidades                        unidades_pkey                           source_id, codigo_unidad
47            raw_mercado              unidades_historial              unidades_historial_pkey                                     observacion_id

In [9]:
indexes = df("""
SELECT
    schemaname AS schema_name,
    tablename AS table_name,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname NOT IN ('pg_catalog','information_schema')
ORDER BY schemaname, tablename, indexname
""")

print("Índices:", len(indexes))
indexes.head(30)

Índices: 100

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

,schema_name,table_name,indexname,indexdef
0,analytics,agg_ventas_mensual,agg_ventas_mensual_pkey,CREATE UNIQUE INDEX agg_ventas_mensual_pkey ON...
1,analytics,agg_ventas_mensual,ix_agg_sales_month_project,CREATE INDEX ix_agg_sales_month_project ON ana...
2,analytics,dim_fecha,dim_fecha_pkey,CREATE UNIQUE INDEX dim_fecha_pkey ON analytic...
3,analytics,dim_periodo_comercial_proyecto,dim_periodo_comercial_proyecto_pkey,CREATE UNIQUE INDEX dim_periodo_comercial_proy...
4,analytics,fact_absorcion_proyecto_diario,fact_absorcion_proyecto_diario_pkey,CREATE UNIQUE INDEX fact_absorcion_proyecto_di...
5,analytics,fact_absorcion_proyecto_diario,ix_abs_project_date,CREATE INDEX ix_abs_project_date ON analytics....
6,analytics,fact_movimientos_stock,fact_movimientos_stock_pkey,CREATE UNIQUE INDEX fact_movimientos_stock_pke...
7,analytics,fact_stock_ofertado_diario,fact_stock_ofertado_diario_pkey,CREATE UNIQUE INDEX fact_stock_ofertado_diario...
8,analytics,fact_stock_ofertado_diario,ix_fact_stock_project_date,CREATE INDEX ix_fact_stock_project_date ON ana...
9,analytics,fact_ventas_detalle,fact_ventas_detalle_codigo_proforma_codigo_uni...,CREATE UNIQUE INDEX fact_ventas_detalle_codigo...
10,analytics,fact_ventas_detalle,fact_ventas_detalle_pkey,CREATE UNIQUE INDEX fact_ventas_detalle_pkey O...
11,analytics,fact_ventas_detalle,ix_fact_ventas_project_date,CREATE INDEX ix_fact_ventas_project_date ON an...
12,analytics,int_ciclo_comercial_unidad,int_ciclo_comercial_unidad_pkey,CREATE UNIQUE INDEX int_ciclo_comercial_unidad...
13,analytics,int_proforma_minuta,int_proforma_minuta_pkey,CREATE UNIQUE INDEX int_proforma_minuta_pkey O...
14,analytics,int_unidad_entrada_stock,int_unidad_entrada_stock_pkey,CREATE UNIQUE INDEX int_unidad_entrada_stock_p...
15,analytics,metric_definitions,metric_definitions_pkey,CREATE UNIQUE INDEX metric_definitions_pkey ON...
16,core,dim_proyecto,dim_proyecto_codigo_proyecto_key,CREATE UNIQUE INDEX dim_proyecto_codigo_proyec...
17,core,dim_proyecto,dim_proyecto_pkey,CREATE UNIQUE INDEX dim_proyecto_pkey ON core....
18,core,dim_proyecto,ix_dim_proyecto_distrito,CREATE INDEX ix_dim_proyecto_distrito ON core....
19,core,dim_proyecto,ix_dim_proyecto_estado,CREATE INDEX ix_dim_proyecto_estado ON core.di...
20,core,dim_unidad,dim_unidad_codigo_unidad_key,CREATE UNIQUE INDEX dim_unidad_codigo_unidad_k...
21,core,dim_unidad,dim_unidad_pkey,CREATE UNIQUE INDEX dim_unidad_pkey ON core.di...
22,core,dim_unidad,ix_dim_unidad_estado_comercial,CREATE INDEX ix_dim_unidad_estado_comercial ON...
23,core,dim_unidad,ix_dim_unidad_proyecto,CREATE INDEX ix_dim_unidad_proyecto ON core.di...
24,core,dim_unidad,ix_dim_unidad_tipo,CREATE INDEX ix_dim_unidad_tipo ON core.dim_un...
25,core,dim_unidad,ix_dim_unidad_tipologia_ubicacion,CREATE INDEX ix_dim_unidad_tipologia_ubicacion...
26,decision_intelligence,actions,actions_pkey,CREATE UNIQUE INDEX actions_pkey ON decision_i...
27,decision_intelligence,candidate_universe_snapshot,candidate_universe_snapshot_pkey,CREATE UNIQUE INDEX candidate_universe_snapsho...
28,decision_intelligence,candidate_universe_snapshot,ix_candidate_universe_snapshot_entity,CREATE INDEX ix_candidate_universe_snapshot_en...
29,decision_intelligence,decision_contracts,decision_contracts_pkey,CREATE UNIQUE INDEX decision_contracts_pkey ON...

## 4. Radar de frescura

Busca automáticamente columnas cuyo nombre sugiera fecha/hora y estima la última observación disponible.

In [10]:
DATE_HINTS = (
    "fecha", "date", "created", "updated", "timestamp",
    "inicio", "fin", "carga", "sync", "etl", "inserted", "modified"
)

date_candidates = columns[
    columns["data_type"].str.contains("date|timestamp", case=False, na=False)
    & columns["column_name"].str.lower().apply(
        lambda x: any(h in x for h in DATE_HINTS)
    )
].copy()

priority_words = [
    "updated", "modified", "carga", "sync", "etl",
    "fecha_actualizacion", "fecha_modificacion",
    "created", "fecha_creacion", "fecha"
]

def priority(col):
    c = col.lower()
    for i, word in enumerate(priority_words):
        if word in c:
            return i
    return 999

date_candidates["priority"] = date_candidates["column_name"].map(priority)
date_candidates = date_candidates.sort_values(
    ["schema_name","table_name","priority","ordinal_position"]
)

date_candidates.head(40)

    schema_name                      table_name  ordinal_position                                 column_name                 data_type is_nullable  priority
9     analytics                       dim_fecha                 1                                       fecha                      date          NO         9
21    analytics  dim_periodo_comercial_proyecto                 3                fecha_inicio_venta_declarada                      date         YES         9
22    analytics  dim_periodo_comercial_proyecto                 4            fecha_inicio_comercial_observada                      date         YES         9
23    analytics  dim_periodo_comercial_proyecto                 5  fecha_ultima_actividad_comercial_observada                      date         YES         9
26    analytics  fact_absorcion_proyecto_diario                 1                                       fecha                      date          NO         9
70    analytics          fact_movimientos_stock                 8                                fecha_evento                      date          NO         9
82    analytics      fact_stock_ofertado_diario                 1                                       fecha                      date          NO         9
102   analytics             fact_ventas_detalle                 8                         fecha_entrada_stock                      date         YES         9
103   analytics             fact_ventas_detalle                 9                        fecha_separacion_raw                      date         YES         9
104   analytics             fact_ventas_detalle                10                            fecha_separacion                      date         YES         9
105   analytics             fact_ventas_detalle                11                          fecha_firma_legacy                      date         YES         9
106   analytics             fact_ventas_detalle                12                             fecha_de_minuta                      date         YES         9
107   analytics             fact_ventas_detalle                13                      fecha_venta_documental                      date         YES         9
108   analytics             fact_ventas_detalle                14                                 fecha_venta                      date          NO         9
110   analytics             fact_ventas_detalle                16                         primera_fecha_caida                      date         YES         9
125   analytics      int_ciclo_comercial_unidad                 5                         fecha_entrada_stock                      date         YES         9
126   analytics      int_ciclo_comercial_unidad                 6                        fecha_separacion_raw                      date         YES         9
127   analytics      int_ciclo_comercial_unidad                 7                            fecha_separacion                      date         YES         9
130   analytics      int_ciclo_comercial_unidad                10                          fecha_firma_legacy                      date         YES         9
132   analytics      int_ciclo_comercial_unidad                12                             fecha_de_minuta                      date         YES         9
133   analytics      int_ciclo_comercial_unidad                13                                 fecha_venta                      date         YES         9
135   analytics      int_ciclo_comercial_unidad                15                         primera_fecha_caida                      date         YES         9
136   analytics      int_ciclo_comercial_unidad                16                          ultima_fecha_caida                      date         YES         9
146   analytics      int_ciclo_comercial_unidad                26                               fecha_pago_ci                      date         YES         9
155   analytics             int_proforma_minuta                 9                        fecha_separacion_raw                      date         YES         9
156   analytics             int_proforma_minuta                10                         fecha_entrada_stock                      date         YES         9
157   analytics             int_proforma_minuta                11                  fecha_separacion_analitica                      date         YES         9
162   analytics             int_proforma_minuta                16                             fecha_de_minuta                      date         YES         9
173   analytics             int_proforma_minuta                27                               fecha_pago_ci                      date         YES         9
176   analytics        int_unidad_entrada_stock                 3                         fecha_entrada_stock                      date          NO         9
189   analytics              metric_definitions                 8                                  created_at  timestamp with time zone          NO         7
190   analytics    v_absorcion_proyecto_current                 1                                       fecha                      date         YES         9
228   analytics    v_absorcion_proyecto_current                39            fecha_inicio_comercial_observada                      date         YES         9
233   analytics  v_ciclo_comercial_reconciliado                 5                         fecha_entrada_stock                      date         YES         9
234   analytics  v_ciclo_comercial_reconciliado                 6                        fecha_separacion_raw                      date         YES         9
235   analytics  v_ciclo_comercial_reconciliado                 7                            fecha_separacion                      date         YES         9
238   analytics  v_ciclo_comercial_reconciliado                10                          fecha_firma_legacy                      date         YES         9
240   analytics  v_ciclo_comercial_reconciliado                12                             fecha_de_minuta                      date         YES         9
241   analytics  v_ciclo_comercial_reconciliado                13                                 fecha_venta                      date         YES         9
243   analytics  v_ciclo_comercial_reconciliado                15                         primera_fecha_caida                      date         YES         9

In [11]:
MAX_FRESHNESS_TABLES = 60

table_sizes = inventory[
    inventory["object_type"].isin(["table","partitioned_table"])
][["schema_name","object_name","approx_rows","bytes"]].rename(
    columns={"object_name":"table_name"}
)

targets = (
    date_candidates
    .drop_duplicates(["schema_name","table_name"])
    .merge(table_sizes, on=["schema_name","table_name"], how="left")
    .sort_values(["bytes","approx_rows"], ascending=False)
    .head(MAX_FRESHNESS_TABLES)
)

freshness_rows = []

for r in targets.itertuples():
    schema, table, col = r.schema_name, r.table_name, r.column_name

    qschema = '"' + schema.replace('"','""') + '"'
    qtable = '"' + table.replace('"','""') + '"'
    qcol = '"' + col.replace('"','""') + '"'

    try:
        x = df(f'SELECT MAX({qcol}) AS max_ts FROM {qschema}.{qtable}')
        max_ts = x.iloc[0,0]
        freshness_rows.append((schema, table, col, max_ts, None))
    except Exception as exc:
        conn.rollback()
        freshness_rows.append(
            (schema, table, col, None, str(exc)[:180])
        )

freshness = pd.DataFrame(
    freshness_rows,
    columns=["schema_name","table_name","date_column","max_ts","error"]
)

freshness["max_ts"] = pd.to_datetime(
    freshness["max_ts"], errors="coerce", utc=True
)

now_utc = pd.Timestamp.now(tz="UTC")
freshness["age_hours"] = (
    now_utc - freshness["max_ts"]
).dt.total_seconds() / 3600

freshness.sort_values("age_hours", na_position="last").head(40)

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

              schema_name                                      table_name                 date_column                           max_ts error   age_hours
23          observability                                  asset_registry                  updated_at 2026-09-07 02:38:54.445100+00:00  None    0.435579
13            etl_control                                       sync_runs                 finished_at 2026-09-07 02:34:44.885838+00:00  None    0.504901
14          observability                                 asset_snapshots        last_run_finished_at 2026-09-07 02:34:44.885838+00:00  None    0.504901
26            etl_control                                      sync_state                  updated_at 2026-09-07 02:34:44.884419+00:00  None    0.504901
7              raw_cygnus                                    datos_extras              _etl_loaded_at 2026-09-07 02:34:44.877777+00:00  None    0.504903
36             raw_cygnus                                       proyectos              _etl_loaded_at 2026-09-07 02:34:42.342785+00:00  None    0.505607
8              raw_cygnus                                        unidades              _etl_loaded_at 2026-09-07 02:34:39.302699+00:00  None    0.506452
3              raw_cygnus                                 proforma_unidad              _etl_loaded_at 2026-09-07 02:34:36.960277+00:00  None    0.507102
4              raw_cygnus                                       proformas              _etl_loaded_at 2026-09-07 02:34:34.027155+00:00  None    0.507917
2              raw_cygnus                                        clientes              _etl_loaded_at 2026-09-07 02:34:31.046490+00:00  None    0.508745
0              raw_cygnus                                   interacciones              _etl_loaded_at 2026-09-07 02:34:27.646214+00:00  None    0.509690
6              raw_cygnus                                        procesos              _etl_loaded_at 2026-09-07 02:34:24.861714+00:00  None    0.510463
1              raw_cygnus                              clientes_proyectos              _etl_loaded_at 2026-09-07 02:34:22.843975+00:00  None    0.511024
30  decision_intelligence                              decision_contracts                  updated_at 2026-09-07 02:32:05.034803+00:00  None    0.549304
12                   core                                      dim_unidad  fecha_actualizacion_origen        2026-09-06 00:00:00+00:00  None   27.084036
20              analytics                             int_proforma_minuta        fecha_separacion_raw        2026-09-06 00:00:00+00:00  None   27.084036
25                   core                                    dim_proyecto  fecha_actualizacion_origen        2026-09-06 00:00:00+00:00  None   27.084036
45  decision_intelligence                   v_fall_reason_analysis_corpus     motivo_caida_updated_at        2026-09-06 00:00:00+00:00  None   27.084036
46  decision_intelligence                  v_fall_reason_proforma_history     motivo_caida_updated_at        2026-09-06 00:00:00+00:00  None   27.084036
50  decision_intelligence                  v_proforma_outcome_text_latest     motivo_caida_updated_at        2026-09-06 00:00:00+00:00  None   27.084036
53  decision_intelligence              v_separation_fall_training_outcome     motivo_caida_updated_at        2026-09-06 00:00:00+00:00  None   27.084036
54               features                    separation_fall_risk_current            fecha_separacion        2026-09-06 00:00:00+00:00  None   27.084036
58               features            v_separation_fall_training_30d_audit            fecha_separacion        2026-09-06 00:00:00+00:00  None   27.084036
57               features       v_separation_fall_risk_candidate_universe            fecha_separacion        2026-09-06 00:00:00+00:00  None   27.084036
44  decision_intelligence             v_department_transfer_lineage_audit            fecha_separacion        2026-09-06 00:00:00+00:00  None   27.084036
51  decision_intelligence               v_separation_fall_outcome_history     motivo_caida_updated_at        2026-09-06 00:00:00+00:00  None   27.084036
41              analytics                       v_inventory_state_current             last_event_date        2026-09-06 00:00:00+00:00  None   27.084036
11              analytics                          fact_movimientos_stock                fecha_evento        2026-09-06 00:00:00+00:00  None   27.084036
18              analytics                        int_unidad_entrada_stock         fecha_entrada_stock        2026-09-05 00:00:00+00:00  None   51.084036
19            raw_mercado                                        unidades                  cargado_en 2026-09-04 14:05:19.436451+00:00  None   60.995304
17            raw_mercado                              unidades_historial                  cargado_en 2026-09-04 14:05:19.436451+00:00  None   60.995304
28            raw_mercado                                          cargas              fecha_snapshot        2026-09-04 00:00:00+00:00  None   75.084036
40              analytics                  v_ciclo_comercial_reconciliado         fecha_entrada_stock        2026-09-03 00:00:00+00:00  None   99.084036
43                   core                     fact_ciclo_comercial_unidad         fecha_entrada_stock        2026-09-03 00:00:00+00:00  None   99.084036
15              analytics                      int_ciclo_comercial_unidad         fecha_entrada_stock        2026-09-03 00:00:00+00:00  None   99.084036
59               features  v_separation_fall_training_point_in_time_audit            fecha_separacion        2026-08-31 00:00:00+00:00  None  171.084036
55               features                    separation_fall_training_30d            fecha_separacion        2026-08-29 00:00:00+00:00  None  219.084036
56               features          separation_fall_training_point_in_time            fecha_separacion        2026-08-29 00:00:00+00:00  None  219.084036
33  decision_intelligence                                 policy_registry                  updated_at 2026-08-18 13:32:46.746204+00:00  None  469.537717
22  decision_intelligence                                  recommendation                  created_at 2026-08-18 09:30:03.610767+00:00  None  473.583033

In [12]:
def freshness_label(hours):
    if pd.isna(hours):
        return "SIN FECHA"
    if hours <= 2:
        return "OK <=2h"
    if hours <= 24:
        return "REVISAR <=24h"
    if hours <= 72:
        return "STALE 1-3d"
    return "STALE >3d"

freshness["status"] = freshness["age_hours"].map(freshness_label)
freshness["status"].value_counts(dropna=False)

status
STALE >3d     23
STALE 1-3d    17
OK <=2h       14
SIN FECHA      6
Name: count, dtype: int64

## 5. Radar de anomalías estructurales

In [13]:
tables_only = inventory[
    inventory["object_type"].isin(["table","partitioned_table"])
].copy()

pk_keys = set(zip(pk["schema_name"], pk["table_name"]))

tables_only["has_pk"] = [
    (s,t) in pk_keys
    for s,t in zip(tables_only["schema_name"], tables_only["object_name"])
]

tables_only["size_mb"] = tables_only["bytes"] / 1024**2

tables_only["hours_since_autoanalyze"] = (
    pd.Timestamp.now(tz="UTC")
    - pd.to_datetime(
        tables_only["last_autoanalyze"],
        errors="coerce",
        utc=True
    )
).dt.total_seconds() / 3600

anomaly_radar = tables_only.assign(
    flag_empty=lambda x: x["approx_rows"].fillna(0).eq(0),
    flag_no_pk=lambda x: ~x["has_pk"],
    flag_large=lambda x: x["size_mb"].gt(100),
    flag_analyze_old=lambda x: x["hours_since_autoanalyze"].gt(24*7),
)

anomaly_radar["risk_points"] = (
    anomaly_radar["flag_empty"].astype(int)
    + anomaly_radar["flag_no_pk"].astype(int)
    + anomaly_radar["flag_large"].astype(int)
    + anomaly_radar["flag_analyze_old"].astype(int)
)

anomaly_radar.sort_values(
    ["risk_points","size_mb"], ascending=False
)[[
    "schema_name","object_name","approx_rows",
    "size_mb","has_pk","last_autoanalyze","risk_points"
]].head(40)

              schema_name                             object_name  approx_rows     size_mb  has_pk                 last_autoanalyze  risk_points
0              raw_cygnus                           interacciones         2525  319.554688   False                              NaT            2
12             raw_cygnus  procesos_backup_keyfix_20260812_002329            0    2.703125   False                              NaT            2
1                features                           lead_evidence       205947  220.398438    True 2026-09-07 02:40:10.734095+00:00            1
2              raw_cygnus                      clientes_proyectos          717   73.039062   False                              NaT            1
3              raw_cygnus                                clientes       141559   69.968750   False 2026-09-06 22:36:15.779475+00:00            1
4              raw_cygnus                         proforma_unidad        44232   17.109375   False 2026-09-06 19:59:25.260605+00:00            1
5              raw_cygnus                               proformas        38008   11.328125   False 2026-09-06 19:58:24.970108+00:00            1
6               analytics          fact_absorcion_proyecto_diario            0    7.929688    True                              NaT            1
7              raw_cygnus                                procesos         5148    5.812500   False 2026-09-06 22:35:13.603469+00:00            1
8              raw_cygnus                            datos_extras        22429    4.296875   False 2026-09-05 10:47:32.547843+00:00            1
9              raw_cygnus                                unidades         3237    4.148438   False 2026-09-07 02:35:23.834407+00:00            1
10              analytics              fact_stock_ofertado_diario            0    4.125000    True                              NaT            1
17              analytics                     fact_ventas_detalle            0    0.515625    True                              NaT            1
23              analytics                               dim_fecha            0    0.296875    True                              NaT            1
25  decision_intelligence                          recommendation            0    0.187500    True                              NaT            1
26              analytics                      agg_ventas_mensual            0    0.156250    True                              NaT            1
28       platform_control                      readiness_controls            0    0.109375    True                              NaT            1
31       platform_control                    application_registry            0    0.070312    True                              NaT            1
33            etl_control                     business_exclusions            0    0.046875    True                              NaT            1
34              analytics          dim_periodo_comercial_proyecto            0    0.031250    True                              NaT            1
35              analytics                      metric_definitions            0    0.031250    True                              NaT            1
37  decision_intelligence                             lead_scores            0    0.031250    True                              NaT            1
38  decision_intelligence                         policy_registry            0    0.031250    True                              NaT            1
39  decision_intelligence                         recommendations            0    0.031250    True                              NaT            1
40       platform_control                              milestones            0    0.031250    True                              NaT            1
41  decision_intelligence             candidate_universe_snapshot            0    0.023438    True                              NaT            1
42  decision_intelligence                            decision_run            0    0.023438    True                              NaT            1
43  decision_intelligence                                outcomes            0    0.023438    True                              NaT            1
44          model_control                              model_runs            0    0.023438    True                              NaT            1
45          model_control                         scoring_batches            0    0.023438    True                              NaT            1
46  decision_intelligence                                 actions            0    0.015625    True                              NaT            1
47  decision_intelligence                   experiment_assignment            0    0.015625    True                              NaT            1
48  decision_intelligence                     experiment_registry            0    0.015625    True                              NaT            1
49  decision_intelligence                     production_incident            0    0.015625    True                              NaT            1
50  decision_intelligence                      quality_gate_event            0    0.015625    True                              NaT            1
51  decision_intelligence                 recommendation_feedback            0    0.015625    True                              NaT            1
52  decision_intelligence                  recommendation_outcome            0    0.015625    True                              NaT            1
53            experiments                             assignments            0    0.015625    True                              NaT            1
54            experiments                             experiments            0    0.015625    True                              NaT            1
55          model_control                           model_aliases            0    0.015625    True                              NaT            1

## 6. Capacidades de plataforma / Decision Intelligence existentes

In [14]:
keywords = [
    "observ", "control", "decision", "experiment",
    "model", "feature", "quality", "audit",
    "score", "lead", "risk"
]

platform_objects = inventory[
    inventory["schema_name"].str.lower().apply(
        lambda s: any(k in s for k in keywords)
    )
    | inventory["object_name"].str.lower().apply(
        lambda s: any(k in s for k in keywords)
    )
].copy()

platform_objects[[
    "schema_name","object_name","object_type","approx_rows","total_size"
]].sort_values(["schema_name","object_name"]).head(100)

               schema_name                                      object_name object_type  approx_rows total_size
46   decision_intelligence                                          actions       table            0      16 kB
41   decision_intelligence                      candidate_universe_snapshot       table            0      24 kB
36   decision_intelligence                               decision_contracts       table            1      32 kB
42   decision_intelligence                                     decision_run       table            0      24 kB
47   decision_intelligence                            experiment_assignment       table            0      16 kB
48   decision_intelligence                              experiment_registry       table            0      16 kB
37   decision_intelligence                                      lead_scores       table            0      32 kB
43   decision_intelligence                                         outcomes       table            0      24 kB
38   decision_intelligence                                  policy_registry       table            0      32 kB
49   decision_intelligence                              production_incident       table            0      16 kB
50   decision_intelligence                               quality_gate_event       table            0      16 kB
25   decision_intelligence                                   recommendation       table            0     192 kB
51   decision_intelligence                          recommendation_feedback       table            0      16 kB
52   decision_intelligence                           recommendation_outcome       table            0      16 kB
39   decision_intelligence                                  recommendations       table            0      32 kB
64   decision_intelligence             v_candidate_universe_snapshot_health        view           -1    0 bytes
65   decision_intelligence                       v_decision_value_scorecard        view           -1    0 bytes
66   decision_intelligence              v_department_transfer_lineage_audit        view           -1    0 bytes
67   decision_intelligence             v_department_transfer_lineage_health        view           -1    0 bytes
68   decision_intelligence                    v_fall_reason_analysis_corpus        view           -1    0 bytes
69   decision_intelligence                    v_fall_reason_analysis_health        view           -1    0 bytes
70   decision_intelligence                   v_fall_reason_proforma_history        view           -1    0 bytes
71   decision_intelligence                                  v_feedback_loop        view           -1    0 bytes
72   decision_intelligence                            v_lead_action_outcome        view           -1    0 bytes
73   decision_intelligence                v_lead_action_outcome_performance        view           -1    0 bytes
74   decision_intelligence                          v_lead_priority_current        view           -1    0 bytes
75   decision_intelligence                 v_lead_score_matured_performance        view           -1    0 bytes
76   decision_intelligence                      v_policy_operational_health        view           -1    0 bytes
77   decision_intelligence                   v_proforma_outcome_text_latest        view           -1    0 bytes
78   decision_intelligence                 v_separation_fall_outcome_health        view           -1    0 bytes
79   decision_intelligence                v_separation_fall_outcome_history        view           -1    0 bytes
80   decision_intelligence                    v_separation_fall_risk_latest        view           -1    0 bytes
81   decision_intelligence                  v_separation_fall_risk_worklist        view           -1    0 bytes
82   decision_intelligence               v_separation_fall_training_outcome        view           -1    0 bytes
83   decision_intelligence        v_separation_fall_training_outcome_health        view           -1    0 bytes
33             etl_control                              business_exclusions       table            0      48 kB
15             etl_control                                        sync_runs       table         2178     896 kB
30             etl_control                                       sync_state       table            9      72 kB
53             experiments                                      assignments       table            0      16 kB
54             experiments                                      experiments       table            0      16 kB
1                 features                                    lead_evidence       table       205947     220 MB
84                features                     separation_fall_risk_current        view           -1    0 bytes
85                features                     separation_fall_training_30d        view           -1    0 bytes
86                features           separation_fall_training_point_in_time        view           -1    0 bytes
87                features        v_separation_fall_risk_candidate_universe        view           -1    0 bytes
88                features                    v_separation_fall_risk_health        view           -1    0 bytes
89                features             v_separation_fall_training_30d_audit        view           -1    0 bytes
90                features            v_separation_fall_training_30d_health        view           -1    0 bytes
91                features    v_separation_fall_training_30d_regime_profile        view           -1    0 bytes
92                features      v_separation_fall_training_landmark_profile        view           -1    0 bytes
93                features        v_separation_fall_training_period_profile        view           -1    0 bytes
94                features   v_separation_fall_training_point_in_time_audit        view           -1    0 bytes
95                features  v_separation_fall_training_point_in_time_health        view           -1    0 bytes
96                features             v_separation_fall_training_readiness        view           -1    0 bytes
55           model_control                                    model_aliases       table            0      16 kB
56           model_control                                 model_promotions       table            0      16 kB
44           model_control                                       model_runs       table            0      24 kB
45           model_control                                  scoring_batches       table            0      24 kB
97           model_control                             v_lead_model_aliases        view           -1    0 bytes
21           observability                       absorption_quality_results       table         2049     440 kB
27           observability                                   asset_registry       table            9     128 kB
16           observability                                  asset_snapshots       table         2219     832 kB
11           observability                                   quality_checks       table         8908    3256 kB
98           observability              v_absorption_reconciliation_current        view           -1    0 bytes
99           observability                           v_asset_health_current        view           -1    0 bytes
100          observability                          v_asset_quality_current        view           -1    0 bytes
101          observability                          v_decision_health_daily        view           -1    0 bytes
102          observability                           v_model_health_current        view           -1    0 bytes
103          observability                                  v_pipeline_runs        view           -1    0 bytes
104          observability                                 v_quality_checks        view           -1    0 bytes
31        platform_control                             application_registry       table            0      72 kB
40        platform_control                                       milestones       table            0      32 kB
28        platform_control                               readiness_controls       table            0     112 kB
105       platform_control                          v_application_readiness        view           -1    0 bytes
106       platform_control                               v_platform_summary        view           -1    0 bytes

## 7. Descubrimiento CRM/comercial

In [15]:
commercial_terms = [
    "cliente", "clientes", "lead",
    "interaccion", "interacciones",
    "proforma", "proformas",
    "proceso", "procesos",
    "separacion", "venta", "minuta",
    "unidad", "unidades", "proyecto"
]

commercial_objects = inventory[
    inventory["object_name"].str.lower().apply(
        lambda s: any(term in s for term in commercial_terms)
    )
].copy()

commercial_objects[[
    "schema_name","object_name","object_type","approx_rows","total_size"
]].sort_values(
    ["schema_name","approx_rows"],
    ascending=[True,False]
).head(100)

               schema_name                             object_name object_type  approx_rows total_size
20               analytics                int_unidad_entrada_stock       table         2720     448 kB
18               analytics              int_ciclo_comercial_unidad       table         2007     528 kB
24               analytics                     int_proforma_minuta       table         1175     304 kB
6                analytics          fact_absorcion_proyecto_diario       table            0    8120 kB
17               analytics                     fact_ventas_detalle       table            0     528 kB
26               analytics                      agg_ventas_mensual       table            0     160 kB
34               analytics          dim_periodo_comercial_proyecto       table            0      32 kB
58               analytics            v_absorcion_proyecto_current        view           -1    0 bytes
61               analytics                v_stock_proyecto_current        view           -1    0 bytes
14                    core                              dim_unidad       table         3237    1304 kB
29                    core                            dim_proyecto       table           18      80 kB
62                    core             fact_ciclo_comercial_unidad        view           -1    0 bytes
37   decision_intelligence                             lead_scores       table            0      32 kB
70   decision_intelligence          v_fall_reason_proforma_history        view           -1    0 bytes
72   decision_intelligence                   v_lead_action_outcome        view           -1    0 bytes
73   decision_intelligence       v_lead_action_outcome_performance        view           -1    0 bytes
74   decision_intelligence                 v_lead_priority_current        view           -1    0 bytes
75   decision_intelligence        v_lead_score_matured_performance        view           -1    0 bytes
77   decision_intelligence          v_proforma_outcome_text_latest        view           -1    0 bytes
1                 features                           lead_evidence       table       205947     220 MB
97           model_control                    v_lead_model_aliases        view           -1    0 bytes
3               raw_cygnus                                clientes       table       141559      70 MB
4               raw_cygnus                         proforma_unidad       table        44232      17 MB
5               raw_cygnus                               proformas       table        38008      11 MB
7               raw_cygnus                                procesos       table         5148    5952 kB
9               raw_cygnus                                unidades       table         3237    4248 kB
0               raw_cygnus                           interacciones       table         2525     320 MB
2               raw_cygnus                      clientes_proyectos       table          717      73 MB
57              raw_cygnus                               proyectos       table           18      16 kB
12              raw_cygnus  procesos_backup_keyfix_20260812_002329       table            0    2768 kB
19             raw_mercado                      unidades_historial       table          696     496 kB
22             raw_mercado                                unidades       table          696     384 kB
107            raw_mercado                       v_unidades_actual        view           -1    0 bytes

## 8. Perfil rápido de una tabla

Modifica `TARGET_SCHEMA` y `TARGET_TABLE` para explorar cualquier tabla.

In [16]:
_candidates = commercial_objects[
    commercial_objects["object_type"].isin(["table","partitioned_table"])
]

if _candidates.empty:
    _candidates = inventory[
        inventory["object_type"].isin(["table","partitioned_table"])
    ]

TARGET_SCHEMA = _candidates.iloc[0]["schema_name"]
TARGET_TABLE = _candidates.iloc[0]["object_name"]

print("TARGET:", f"{TARGET_SCHEMA}.{TARGET_TABLE}")

TARGET: raw_cygnus.interacciones

In [17]:
def quote_ident(x: str) -> str:
    return '"' + x.replace('"','""') + '"'

def profile_table(schema: str, table: str, sample_rows: int = 10):
    qschema, qtable = quote_ident(schema), quote_ident(table)

    meta = columns[
        (columns["schema_name"] == schema)
        & (columns["table_name"] == table)
    ].copy()

    sample = df(
        f"SELECT * FROM {qschema}.{qtable} LIMIT {int(sample_rows)}"
    )

    count = df(
        f"SELECT COUNT(*) AS rows FROM {qschema}.{qtable}"
    ).iloc[0,0]

    print(f"{schema}.{table}")
    print(f"Filas exactas: {count:,}")
    print(f"Columnas: {len(meta):,}")

    display(
        meta[
            ["ordinal_position","column_name","data_type","is_nullable"]
        ]
    )
    display(sample)

    return meta, sample, count

target_meta, target_sample, target_count = profile_table(
    TARGET_SCHEMA,
    TARGET_TABLE
)

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)
C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

raw_cygnus.interacciones
Filas exactas: 803,163
Columnas: 44

      ordinal_position                  column_name                    data_type is_nullable
1719                 1              nombres_usuario            character varying         YES
1720                 2                     username            character varying         YES
1721                 3              nombres_cliente            character varying         YES
1722                 4            apellidos_cliente            character varying         YES
1723                 5            documento_cliente            character varying         YES
1724                 6                canal_entrada            character varying         YES
1725                 7              medio_captacion            character varying         YES
1726                 8             tipo_interaccion            character varying         YES
1727                 9                       nombre            character varying         YES
1728                10              codigo_proyecto            character varying         YES
1729                11              nombre_proyecto            character varying         YES
1730                12                codigo_unidad            character varying         YES
1731                13                nombre_unidad            character varying         YES
1732                14             fecha_programada                         date         YES
1733                15                       estado            character varying         YES
1734                16                  observacion            character varying         YES
1735                17                   utm_source            character varying         YES
1736                18                   utm_medium            character varying         YES
1737                19                 utm_campaign            character varying         YES
1738                20                     utm_term            character varying         YES
1739                21                  utm_content            character varying         YES
1740                22                       origen            character varying         YES
1741                23                           id                      integer         YES
1742                24                         tipo            character varying         YES
1743                25               fecha_creacion  timestamp without time zone         YES
1744                26                satisfactorio            character varying         YES
1745                27           clientes_invitados            character varying         YES
1746                28          contactos_invitados            character varying         YES
1747                29           usuarios_invitados            character varying         YES
1748                30                   cliente_id                      integer         YES
1749                31                  tipo_evento            character varying         YES
1750                32                nivel_interes            character varying         YES
1751                33  categorias_tipo_interaccion            character varying         YES
1752                34          fecha_actualizacion                         date         YES
1753                35          razon_desistimiento            character varying         YES
1754                36           hora_actualizacion            character varying         YES
1755                37              codigo_proforma            character varying         YES
1756                38                origen_manual            character varying         YES
1757                39                     segmento            character varying         YES
1758                40            vendedor_asignado            character varying         YES
1759                41         canal_entrada_rastro            character varying         YES
1760                42       medio_captacion_rastro            character varying         YES
1761                43               _etl_loaded_at     timestamp with time zone          NO
1762                44           _etl_source_run_id                         uuid         YES

,nombres_usuario,username,nombres_cliente,apellidos_cliente,documento_cliente,canal_entrada,medio_captacion,tipo_interaccion,nombre,codigo_proyecto,nombre_proyecto,codigo_unidad,nombre_unidad,fecha_programada,estado,observacion,utm_source,utm_medium,utm_campaign,utm_term,utm_content,origen,id,tipo,fecha_creacion,satisfactorio,clientes_invitados,contactos_invitados,usuarios_invitados,cliente_id,tipo_evento,nivel_interes,categorias_tipo_interaccion,fecha_actualizacion,razon_desistimiento,hora_actualizacion,codigo_proforma,origen_manual,segmento,vendedor_asignado,canal_entrada_rastro,medio_captacion_rastro,_etl_loaded_at,_etl_source_run_id
0,Cinthia Román Villavicencio,croman,Luzmirian,Sanchez,auto-349010,por email,facebook,creación de cliente,creación de cliente,CRUZ,Edificio Santa Cruz Infinite,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Santa Cruz diciembre,None,None,fblead,6666,ACTIVIDAD,2020-01-26 23:54:26,si,None,None,None,4125,None,por contactar,None,2020-03-10,None,14:21:10,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
1,Joceline Arizabal Corimanya,jarizabal,Ariadna,Baiocchi,auto-455010,None,None,facebook,facebook,ES,Edificio Saenz,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Saenz diciembre,None,None,fblead,6667,ACTIVIDAD,2020-01-24 01:08:58,si,None,None,None,4122,None,por contactar,None,2020-03-10,None,14:21:10,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
2,Nelly Román Villavicencio,nroman,Nestor,Alegria,auto-583012,None,None,facebook,facebook,CUBA,Edificio Cuba Connect,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Cuba Diciembre,None,None,fblead,6668,ACTIVIDAD,2020-01-23 02:22:40,si,None,None,None,4124,None,por contactar,None,2020-03-10,None,14:21:10,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
3,Cinthia Román Villavicencio,croman,Luzmirian,Sanchez,auto-349010,None,None,facebook,facebook,CRUZ,Edificio Santa Cruz Infinite,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Santa Cruz diciembre,None,None,fblead,6669,ACTIVIDAD,2020-01-26 23:54:26,si,None,None,None,4125,None,por contactar,None,2020-03-10,None,14:21:10,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
4,Jackeline Espichan Medina,jespichan,Betzi,Rivera,auto-466725,por email,facebook,creación de cliente,creación de cliente,URT,Los Jardines de Urteaga,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Urteaga Diciembre,None,None,fblead,6670,ACTIVIDAD,2020-02-10 21:41:03,si,None,None,None,4126,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
5,Joceline Arizabal Corimanya,jarizabal,Carla,Gabriela,auto-290588,por email,facebook,creación de cliente,creación de cliente,ES,Edificio Saenz,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Saenz diciembre,None,None,fblead,6671,ACTIVIDAD,2020-01-24 00:30:52,si,None,None,None,4127,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
6,Nelly Román Villavicencio,nroman,Kennys amado,Huaman Benites,auto-411673,por email,facebook,creación de cliente,creación de cliente,CUBA,Edificio Cuba Connect,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Cuba Diciembre,None,None,fblead,6672,ACTIVIDAD,2020-01-22 23:11:26,si,None,None,None,4128,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
7,Jackeline Espichan Medina,jespichan,Betzi,Rivera,auto-466725,None,None,facebook,facebook,URT,Los Jardines de Urteaga,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Urteaga Diciembre,None,None,fblead,6673,ACTIVIDAD,2020-02-10 21:41:03,si,None,None,None,4126,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
8,Cinthia Román Villavicencio,croman,Dianita Chavarry,Puelles,auto-596242,por email,facebook,creación de cliente,creación de cliente,CRUZ,Edificio Santa Cruz Infinite,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Santa Cruz diciembre,None,None,fblead,6674,ACTIVIDAD,2020-01-26 22:05:32,si,None,None,None,4129,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e
9,Joceline Arizabal Corimanya,jarizabal,Carla,Gabriela,auto-290588,None,None,facebook,facebook,ES,Edificio Saenz,None,None,None,realizado,¿qué_es_lo_que_más_importante_para_elegir_un_d...,fblead,social,Saenz diciembre,None,None,fblead,6675,ACTIVIDAD,2020-01-24 00:30:52,si,None,None,None,4127,None,por contactar,None,2020-03-10,None,14:21:11,None,no,None,None,None,None,2026-08-09 02:03:46.036869+00:00,8c86e41e-eadb-42a8-90db-ed566be1da2e

## 9. Calidad de una tabla: nulos + cardinalidad

In [18]:
SAMPLE_LIMIT = 50_000

def sample_quality(schema: str, table: str, limit: int = SAMPLE_LIMIT):
    qschema, qtable = quote_ident(schema), quote_ident(table)

    sample = df(
        f"SELECT * FROM {qschema}.{qtable} LIMIT {int(limit)}"
    )

    rows = []
    n = len(sample)

    for c in sample.columns:
        s = sample[c]

        rows.append({
            "column": c,
            "dtype": str(s.dtype),
            "sample_rows": n,
            "null_pct": float(s.isna().mean() * 100)
                if n else np.nan,
            "nunique": int(s.nunique(dropna=True))
                if n else 0,
            "unique_pct": float(
                s.nunique(dropna=True) / n * 100
            ) if n else np.nan,
        })

    return pd.DataFrame(rows).sort_values(
        ["null_pct","unique_pct"],
        ascending=[False,False]
    )

quality = sample_quality(TARGET_SCHEMA, TARGET_TABLE)
quality.head(50)

C:\Users\dinat\AppData\Local\Temp\ipykernel_11576\1950670527.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  out = pd.read_sql_query(sql, conn, params=params)

                         column                dtype  sample_rows  null_pct  nunique  unique_pct
19                     utm_term               object        50000   100.000        0       0.000
20                  utm_content               object        50000   100.000        0       0.000
26           clientes_invitados               object        50000   100.000        0       0.000
27          contactos_invitados               object        50000   100.000        0       0.000
28           usuarios_invitados               object        50000   100.000        0       0.000
32  categorias_tipo_interaccion               object        50000   100.000        0       0.000
34          razon_desistimiento               object        50000   100.000        0       0.000
38                     segmento               object        50000   100.000        0       0.000
39            vendedor_asignado               object        50000   100.000        0       0.000
40         canal_entrada_rastro               object        50000   100.000        0       0.000
41       medio_captacion_rastro               object        50000   100.000        0       0.000
13             fecha_programada               object        50000    99.888       13       0.026
30                  tipo_evento               object        50000    99.888        2       0.004
11                codigo_unidad               object        50000    98.112      117       0.234
12                nombre_unidad               object        50000    98.112       91       0.182
36              codigo_proforma               object        50000    92.140     3930       7.860
6               medio_captacion               object        50000    63.210       11       0.022
5                 canal_entrada               object        50000    63.210        6       0.012
18                 utm_campaign               object        50000    31.174       18       0.036
31                nivel_interes               object        50000    25.310        9       0.018
17                   utm_medium               object        50000    20.938        5       0.010
16                   utm_source               object        50000    13.646        8       0.016
15                  observacion               object        50000     5.018     8360      16.720
25                satisfactorio               object        50000     4.724        2       0.004
21                       origen               object        50000     4.370        5       0.010
9               codigo_proyecto               object        50000     2.062       14       0.028
10              nombre_proyecto               object        50000     2.062       14       0.028
0               nombres_usuario               object        50000     0.186        9       0.018
1                      username               object        50000     0.186        9       0.018
37                origen_manual               object        50000     0.112        2       0.004
3             apellidos_cliente               object        50000     0.010    12831      25.662
22                           id                int64        50000     0.000    50000     100.000
24               fecha_creacion       datetime64[ns]        50000     0.000    37277      74.554
35           hora_actualizacion               object        50000     0.000    24525      49.050
4             documento_cliente               object        50000     0.000    19237      38.474
29                   cliente_id                int64        50000     0.000    19237      38.474
2               nombres_cliente               object        50000     0.000     7584      15.168
33          fecha_actualizacion               object        50000     0.000      377       0.754
42               _etl_loaded_at  datetime64[ns, UTC]        50000     0.000       22       0.044
8                        nombre               object        50000     0.000       14       0.028
7              tipo_interaccion               object        50000     0.000       12       0.024
14                       estado               object        50000     0.000        2       0.004
23                         tipo               object        50000     0.000        2       0.004
43           _etl_source_run_id               object        50000     0.000        1       0.002

## 10. Duplicados potenciales sobre la PK

In [19]:
target_pk = pk[
    (pk["schema_name"] == TARGET_SCHEMA)
    & (pk["table_name"] == TARGET_TABLE)
]

if target_pk.empty:
    print("⚠️ La tabla seleccionada no tiene PK declarada.")
else:
    pk_cols = [
        x.strip()
        for x in target_pk.iloc[0]["pk_columns"].split(",")
    ]

    select_cols = ", ".join(
        quote_ident(c) for c in pk_cols
    )

    qschema = quote_ident(TARGET_SCHEMA)
    qtable = quote_ident(TARGET_TABLE)

    dup = df(f"""
        SELECT {select_cols}, COUNT(*) AS n
        FROM {qschema}.{qtable}
        GROUP BY {select_cols}
        HAVING COUNT(*) > 1
        ORDER BY n DESC
        LIMIT 100
    """)

    print("PK:", pk_cols)
    print("Duplicados encontrados:", len(dup))
    display(dup)

⚠️ La tabla seleccionada no tiene PK declarada.

## 11. Lectura ejecutiva automática

In [20]:
largest_table = largest.iloc[0] if not largest.empty else None

fresh_ok = int(
    (freshness["age_hours"] <= 2).sum()
) if not freshness.empty else 0

fresh_total = int(
    freshness["age_hours"].notna().sum()
) if not freshness.empty else 0

no_pk = int((~tables_only["has_pk"]).sum())
empty = int(
    tables_only["approx_rows"].fillna(0).eq(0).sum()
)
total_tables = len(tables_only)

print("=== LECTURA EJECUTIVA ===")
print(
    f"• PostgreSQL responde y expone {total_tables:,} tablas "
    f"en {inventory['schema_name'].nunique():,} esquemas."
)

if largest_table is not None:
    print(
        f"• Mayor objeto físico: "
        f"{largest_table['schema_name']}.{largest_table['object_name']} "
        f"≈ {largest_table['approx_rows']:,.0f} filas / "
        f"{largest_table['size_mb']:.1f} MB."
    )

print(
    f"• Frescura detectable <=2h: "
    f"{fresh_ok}/{fresh_total} tablas inspeccionadas con fecha."
)

print(
    f"• Tablas sin PK declarada: "
    f"{no_pk}/{total_tables}."
)

print(
    f"• Tablas reportadas como vacías por estadísticas: "
    f"{empty}/{total_tables}."
)

print(
    f"• Objetos de plataforma/DI detectados: "
    f"{len(platform_objects):,}."
)

print(
    f"• Objetos CRM/comerciales detectados: "
    f"{len(commercial_objects):,}."
)

if fresh_total and fresh_ok / fresh_total < 0.5:
    print(
        "⚠️ Menos de la mitad de las tablas con fecha "
        "parecen frescas <=2h. Revisar si es esperado por dominio."
    )

if total_tables and no_pk > total_tables * 0.5:
    print(
        "⚠️ Más de la mitad de las tablas no declara PK. "
        "No siempre es error, pero complica unicidad y relaciones."
    )

=== LECTURA EJECUTIVA ===
• PostgreSQL responde y expone 58 tablas en 11 esquemas.
• Mayor objeto físico: raw_cygnus.interacciones ≈ 2,525 filas / 319.6 MB.
• Frescura detectable <=2h: 14/54 tablas inspeccionadas con fecha.
• Tablas sin PK declarada: 10/58.
• Tablas reportadas como vacías por estadísticas: 32/58.
• Objetos de plataforma/DI detectados: 75.
• Objetos CRM/comerciales detectados: 33.
⚠️ Menos de la mitad de las tablas con fecha parecen frescas <=2h. Revisar si es esperado por dominio.

## 12. Export opcional a `/reports`

In [23]:
EXPORT = False

if EXPORT:
    out = PROJECT_ROOT / "reports" / "notebook_command_center"
    out.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    inventory.to_csv(
        out / f"inventory_{stamp}.csv",
        index=False
    )
    freshness.to_csv(
        out / f"freshness_{stamp}.csv",
        index=False
    )
    anomaly_radar.to_csv(
        out / f"anomaly_radar_{stamp}.csv",
        index=False
    )
    platform_objects.to_csv(
        out / f"platform_objects_{stamp}.csv",
        index=False
    )
    commercial_objects.to_csv(
        out / f"commercial_objects_{stamp}.csv",
        index=False
    )

    print("Exportado en:", out)
else:
    print(
        "EXPORT=True. Cambia a True "
        "si quieres persistir snapshots."
    )

EXPORT=True. Cambia a True si quieres persistir snapshots.

## 13. Cierre limpio

In [24]:
conn.close()
print("Conexión cerrada.")

Conexión cerrada.